"use client"

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react"
import { useRouter } from "next/navigation"
import type { RunSettings, ScenarioDocument } from "@fillrate/contracts"
import type { CsvImportInput, CsvImportPreview, OrderColumn, InventoryColumn } from "@fillrate/db/imports"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

const orderColumns: OrderColumn[] = ["order_id", "line_id", "order_date", "customer_id", "location_id", "location_label", "address", "latitude", "longitude", "product", "ordered_pieces", "net_value_per_piece", "linear_feet_per_piece"]
const inventoryColumns: InventoryColumn[] = ["product", "available_pieces"]
const templates = { orders: `${orderColumns.join(",")}\nO-1,L-1,2026-09-30,ACME,C-1,Customer 1,,35.1,-90.1,SKU-1,10,12.50,1.25\n`, inventory: "product,available_pieces\nSKU-1,100\n" }
type ScenarioRunSettings = Omit<RunSettings, "objective"> & { objective: "trucks_then_distance" | "weighted_distance" | "cost"; preflight: { missing_coordinates: "block" | "warn"; far_from_depot: "block" | "warn"; oversize_stop: "block" | "warn" }; excluded_line_ids: string[]; cost_per_truck_cents: number | null; cost_per_mile_cents: number | null }
const defaults: ScenarioRunSettings = { schema_version: 1, trailer_capacity: 5300, travel_circuity: 1.2, cluster_circuity: 1.2, max_leg_m: 804672, max_cluster_diameter_m: null, k: null, auto_k_cap: 25, kmeans_seed: 0, kmeans_n_init: 10, max_stops: 500, solver_seed: 0, solver_max_iterations: null, solver_time_limit_s: 10, objective: "trucks_then_distance", weighted_truck_penalty_m: null, preflight: { missing_coordinates: "block", far_from_depot: "block", oversize_stop: "block" }, excluded_line_ids: [], cost_per_truck_cents: null, cost_per_mile_cents: null }
type Saved = { id: string; scenarioId: string; revision: number; parentVersionId: string | null; author: string; document: ScenarioDocument; source: unknown }
type Listed = { id: string; name: string; revision: number; author: string; versionId: string }
type PreflightFinding = { check: "missing_coordinates" | "far_from_depot" | "oversize_stop" | "approximate_coordinates"; action: "block" | "warn"; location_ids: string[]; line_ids: string[]; message: string }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="flex min-w-0 flex-col gap-1.5 text-sm"><span className="font-medium">{label}</span>{children}</label> }
function download(name: string, content: string, type = "text/csv") { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }
function decimal(raw: string) { if (!/^\d+(?:\.\d{1,2})?$/.test(raw)) throw new Error("Use at most two decimal places."); const [whole, fraction = ""] = raw.split("."); const n = BigInt(whole) * BigInt(100) + BigInt(fraction.padEnd(2, "0")); if (n > BigInt(Number.MAX_SAFE_INTEGER)) throw new Error("Value is too large."); return Number(n) }
function EditCell({ label, value, onCommit }: { label: string; value: string | number; onCommit: (value: string) => void }) {
  return <Input key={String(value)} aria-label={label} className="min-w-24" defaultValue={value} onBlur={e => onCommit(e.target.value)} onKeyDown={e => { if (e.key === "Enter") e.currentTarget.blur() }} />
}
export function ScenarioWorkbench() {
  const router = useRouter();
  const [key, setKey] = useState(""); const [author, setAuthor] = useState(""); const [browserId, setBrowserId] = useState("");
  const [timezone, setTimezone] = useState("America/Chicago"); const [planningDate, setPlanningDate] = useState("");
  const [list, setList] = useState<Listed[]>([]); const [saved, setSaved] = useState<Saved | null>(null); const [doc, setDoc] = useState<ScenarioDocument | null>(null);
  const [dirty, setDirty] = useState(false); const [conflict, setConflict] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [input, setInput] = useState<CsvImportInput>({ name: "New scenario", depot: { id: "depot", label: "Depot", lat: 35.1495, lon: -90.049 }, ordersCsv: "", inventoryCsv: "" });
  const [preview, setPreview] = useState<CsvImportPreview | null>(null); const [tab, setTab] = useState("orders"); const [page, setPage] = useState(0);
  const [settings, setSettings] = useState<ScenarioRunSettings>(defaults);
  const [findings, setFindings] = useState<PreflightFinding[]>([]);
  const pendingSave = useRef<{ request: string; key: string } | null>(null);
  useEffect(() => {
    const timeout = window.setTimeout(() => {
      setKey(sessionStorage.getItem("fillrate.scenario-key") ?? ""); setAuthor(localStorage.getItem("fillrate.author.v1") ?? "");
      const id = localStorage.getItem("fillrate.browser.v1") ?? crypto.randomUUID(); localStorage.setItem("fillrate.browser.v1", id); setBrowserId(id);
      setTimezone(Intl.DateTimeFormat().resolvedOptions().timeZone); const now = new Date(); setPlanningDate(`${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`);
    }, 0);
    return () => window.clearTimeout(timeout);
  }, []);
  async function api<T>(path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const response = await fetch(path, { method: body ? "POST" : "GET", headers: { "Content-Type": "application/json", "x-scenario-key": key, ...extraHeaders }, body: body ? JSON.stringify(body) : undefined, cache: "no-store" });
    const data = await response.json(); if (!response.ok) { if (response.status === 409) setConflict(true); throw new Error(data.error?.message ?? data.message ?? JSON.stringify(data)); } return data;
  }
  async function saveRequest(path: string, body: unknown) {
    const request = `${path}:${JSON.stringify(body)}`;
    if (pendingSave.current?.request !== request) pendingSave.current = { request, key: crypto.randomUUID() };
    return api<{ scenarioId: string; versionId: string }>(path, body, { "Idempotency-Key": pendingSave.current.key });
  }
  async function action(fn: () => Promise<void>) { setBusy(true); setMessage(""); try { await fn() } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed.") } finally { setBusy(false) } }
  async function load(id: string, version?: string) { const row = await api<Saved>(`/api/v1/scenarios/${id}${version ? `?version=${version}` : ""}`); setSaved(row); setDoc(row.document); setDirty(false); setConflict(false); setPage(0); setPreview(null); setFindings([]) }
  const metadata = { timezone, planningDate, browserId };
  function changeInput(patch: Partial<CsvImportInput>) { setInput(previous => ({ ...previous, ...patch })); setPreview(null) }
  function changeDocument(fn: (draft: ScenarioDocument) => void) { if (!doc) return; const draft = structuredClone(doc); try { fn(draft); setDoc(draft); setDirty(true); setFindings([]) } catch (e) { setMessage((e as Error).message) } }
  async function save(branch = false) { if (!doc || !saved) return; const ids = await saveRequest(`/api/v1/scenarios/${saved.scenarioId}`, { document: doc, author, metadata, source: saved.source, expectedVersionId: saved.id, branch }); await load(ids.scenarioId, ids.versionId); pendingSave.current = null; setMessage(branch ? "Branch saved." : "Version saved.") }
  const lines = useMemo(() => doc?.orders.flatMap((order, oi) => order.lines.map((line, li) => ({ order, line, oi, li }))) ?? [], [doc]);
  const count = tab === "orders" ? lines.length : tab === "inventory" ? doc?.inventory.length ?? 0 : doc?.locations.length ?? 0;
  const updateSetting = (name: keyof ScenarioRunSettings, value: number | null) => { setSettings(previous => ({ ...previous, [name]: value })); setFindings([]) };
  async function preflight(candidate = settings) { if (!saved) return []; const result = await api<{ findings: PreflightFinding[] }>("/api/v1/scenarios/preflight", { versionId: saved.id, settings: candidate }); setFindings(result.findings); return result.findings }
  async function submit(candidate: ScenarioRunSettings) { if (!saved) return; try { const run = await api<{ id: string }>("/api/v1/scenarios/runs", { versionId: saved.id, settings: candidate }, { "Idempotency-Key": crypto.randomUUID() }); router.push(`/runs/${run.id}`) } catch (error) { await preflight(candidate); throw error } }
  async function reviewAndRun(candidate = settings) { const checked = await preflight(candidate); if (checked.some(finding => finding.action === "block")) { setMessage("Resolve the blocking checks, exclude their lines, or change their policy to warn before running."); return } await submit(candidate) }
  return <div className="space-y-6">
    <section className="rounded-xl border p-4 space-y-4"><h2 className="font-semibold">Workspace access & authorship</h2><p className="text-muted-foreground text-sm">Production uses a shared operator key. Your display name records authorship; it does not grant access.</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Field label="Operator key"><Input type="password" autoComplete="off" value={key} onChange={e => { setKey(e.target.value); sessionStorage.setItem("fillrate.scenario-key", e.target.value) }} /></Field>
      <Field label="Display name"><Input value={author} onChange={e => { setAuthor(e.target.value); localStorage.setItem("fillrate.author.v1", e.target.value) }} /></Field>
      <Field label="Planning date"><Input type="date" value={planningDate} onChange={e => setPlanningDate(e.target.value)} /></Field><Field label="Timezone"><Input value={timezone} onChange={e => setTimezone(e.target.value)} /></Field>
    </div><Button disabled={busy} variant="outline" onClick={() => action(async () => setList((await api<{scenarios: Listed[]}>("/api/v1/scenarios")).scenarios))}>Load scenarios</Button>
      {list.length > 0 && <div className="flex flex-wrap gap-2">{list.map(row => <Button variant="outline" key={row.id} disabled={busy || dirty} onClick={() => action(() => load(row.id))}>{row.name} · v{row.revision}</Button>)}</div>}
    </section>
    <section className="rounded-xl border p-4 space-y-4"><h2 className="font-semibold">Import CSV</h2><p className="text-sm text-muted-foreground">Preview is non-destructive. Dollars and feet accept up to two decimals; quantities are whole pieces. Address-only locations remain unresolved until coordinates are entered. ZIP codes are not coordinates; a ZIP and a Census ZCTA are different geographic concepts.</p>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Scenario name"><Input value={input.name} onChange={e => changeInput({ name: e.target.value })} /></Field><Field label="Depot label"><Input value={input.depot.label} onChange={e => changeInput({ depot: { ...input.depot, label: e.target.value } })} /></Field><Field label="Depot latitude"><Input type="number" step="any" value={input.depot.lat} onChange={e => changeInput({ depot: { ...input.depot, lat: Number(e.target.value) } })} /></Field><Field label="Depot longitude"><Input type="number" step="any" value={input.depot.lon} onChange={e => changeInput({ depot: { ...input.depot, lon: Number(e.target.value) } })} /></Field></div>
      <div className="grid gap-4 lg:grid-cols-2">{(["orders", "inventory"] as const).map(kind => <div className="space-y-3" key={kind}><div className="flex items-center justify-between"><h3 className="text-sm font-medium">{kind === "orders" ? "Order lines" : "Inventory"}</h3><Button variant="ghost" onClick={() => download(`${kind}-template.csv`, templates[kind])}>Download template</Button></div><Input aria-label={`${kind} CSV file`} type="file" accept=".csv,text/csv" onChange={e => { const file = e.target.files?.[0]; if (file) void action(async () => { if (file.size > 5_000_000) throw new Error("CSV exceeds 5 MB."); changeInput({ [kind === "orders" ? "ordersCsv" : "inventoryCsv"]: await file.text() }) }) }} /><textarea aria-label={`${kind} CSV content`} className="min-h-32 w-full rounded-lg border bg-background p-3 font-mono text-xs" placeholder={`Paste ${kind} CSV here`} value={kind === "orders" ? input.ordersCsv : input.inventoryCsv} onChange={e => changeInput({ [kind === "orders" ? "ordersCsv" : "inventoryCsv"]: e.target.value })} /><details><summary className="cursor-pointer text-sm">Column mapping</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">{(kind === "orders" ? orderColumns : inventoryColumns).map(column => <Field key={column} label={column.replaceAll("_", " ")}><Input placeholder={column} value={(kind === "orders" ? input.orderMapping : input.inventoryMapping)?.[column as never] ?? ""} onChange={e => changeInput(kind === "orders" ? { orderMapping: { ...input.orderMapping, [column]: e.target.value || undefined } } : { inventoryMapping: { ...input.inventoryMapping, [column]: e.target.value || undefined } })} /></Field>)}</div></details></div>)}</div>
      <Button disabled={busy || !input.ordersCsv || !input.inventoryCsv} onClick={() => action(async () => setPreview(await api<CsvImportPreview>("/api/v1/imports/preview", input)))}>Preview import</Button>
      {preview && <div className="space-y-3"><p className="font-medium">{preview.valid ? `${preview.document?.orders.length} orders ready to save` : `${preview.errors.length} import errors`}</p>{[...preview.errors, ...preview.warnings].slice(0, 50).map((item, i) => <p className="text-sm" key={i}>{item.file} row {item.row}, {item.column}: {item.message}</p>)}{Object.entries(preview.samples).map(([kind, rows]) => <div key={kind} className="overflow-x-auto"><h3 className="text-sm font-medium">{kind} sample</h3><Table><TableHeader><TableRow>{Object.keys(rows[0] ?? {}).map(h => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row, i) => <TableRow key={i}>{Object.entries(row).map(([h, value]) => <TableCell key={h}>{value}</TableCell>)}</TableRow>)}</TableBody></Table></div>)}<Button disabled={busy || !preview.valid || !author.trim() || dirty} onClick={() => action(async () => { const ids = await saveRequest("/api/v1/imports/commit", { ...input, author, metadata }); await load(ids.scenarioId, ids.versionId); pendingSave.current = null; setMessage("Import saved as version 1.") })}>Save import</Button></div>}
    </section>
    {doc && saved && <section className="rounded-xl border p-4 space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{doc.name}</h2><p className="text-sm text-muted-foreground">Version {saved.revision} · {saved.author} · {dirty ? "Unsaved changes" : "Saved"}{saved.parentVersionId ? ` · parent ${saved.parentVersionId.slice(0, 8)}` : ""}</p></div><div className="flex flex-wrap gap-2">{!conflict && <><Button disabled={busy || !dirty || !author.trim()} onClick={() => action(() => save())}>Save version</Button><Button variant="outline" disabled={busy || !author.trim()} onClick={() => action(() => save(true))}>Save branch</Button><Button variant="outline" disabled={busy} onClick={() => action(() => load(saved.scenarioId))}>Discard changes</Button></>}<Button variant="outline" onClick={() => download(`${doc.name}.json`, JSON.stringify({ document: doc, source: saved.source, versionId: saved.id, metadata }, null, 2), "application/json")}>Export JSON</Button></div></div>
      {conflict && <div role="alert" className="space-y-3 rounded-lg border border-destructive/40 p-3 text-sm"><p>Another version was saved. Choose how to resolve your edits.</p><div className="flex flex-wrap gap-2"><Button disabled={busy || !author.trim()} onClick={() => action(() => save(true))}>Save as branch</Button><Button variant="outline" disabled={busy} onClick={() => action(() => load(saved.scenarioId))}>Discard edits and reload</Button></div></div>}
      <Field label="Scenario name"><Input value={doc.name} onChange={e => changeDocument(d => { d.name = e.target.value })} /></Field>
      <div id="scenario-data" className="flex gap-2">{["orders", "inventory", "locations"].map(value => <Button key={value} variant={tab === value ? "default" : "outline"} onClick={() => { setTab(value); setPage(0) }}>{value === "orders" ? "Order lines" : value === "inventory" ? "Inventory" : "Coordinates"}</Button>)}</div>
      <p className="text-xs text-muted-foreground">Edits apply on Enter or when you leave a field. Save a version before running.</p>
      <div className="overflow-x-auto"><Table><TableHeader><TableRow>{(tab === "orders" ? ["Order", "Date", "Product", "Pieces", "Value / piece ($)", "Feet / piece"] : tab === "inventory" ? ["Product", "Available pieces"] : ["Location", "Latitude", "Longitude", "Provenance"]).map(h => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>
        {tab === "orders" && lines.slice(page * 25, (page + 1) * 25).map(({ order, line, oi, li }) => <TableRow key={line.id}><TableCell>{order.id}</TableCell><TableCell><EditCell label={`Date ${order.id}`} value={order.order_date} onCommit={value => changeDocument(d => { d.orders[oi].order_date = value })} /></TableCell><TableCell>{line.product_id}</TableCell><TableCell><EditCell label={`Pieces ${line.id}`} value={line.ordered_pieces} onCommit={value => changeDocument(d => { if (!/^\d+$/.test(value)) throw new Error("Pieces must be a nonnegative whole number."); d.orders[oi].lines[li].ordered_pieces = Number(value) })} /></TableCell><TableCell><EditCell label={`Value ${line.id}`} value={(line.net_value_per_piece_cents / 100).toFixed(2)} onCommit={value => changeDocument(d => { d.orders[oi].lines[li].net_value_per_piece_cents = decimal(value) })} /></TableCell><TableCell><EditCell label={`Feet ${line.id}`} value={((line.linear_feet_per_piece ?? doc.products.find(p => p.id === line.product_id)!.linear_feet_per_piece) / 100).toFixed(2)} onCommit={value => changeDocument(d => { d.orders[oi].lines[li].linear_feet_per_piece = decimal(value) })} /></TableCell></TableRow>)}
        {tab === "inventory" && doc.inventory.slice(page * 25, (page + 1) * 25).map((item, index) => <TableRow key={item.product_id}><TableCell>{item.product_id}</TableCell><TableCell><EditCell label={`Available ${item.product_id}`} value={item.available_pieces} onCommit={value => changeDocument(d => { if (!/^\d+$/.test(value)) throw new Error("Stock must be a nonnegative whole number."); d.inventory[page * 25 + index].available_pieces = Number(value) })} /></TableCell></TableRow>)}
        {tab === "locations" && doc.locations.slice(page * 25, (page + 1) * 25).map((location, index) => <TableRow key={location.id}><TableCell>{location.label}</TableCell>{(["lat", "lon"] as const).map(axis => <TableCell key={axis}><EditCell label={`${axis} ${location.id}`} value={location[axis] ?? ""} onCommit={value => changeDocument(d => { const number = value.trim() ? Number(value) : null; if (number !== null && (!Number.isFinite(number) || Math.abs(number) > (axis === "lat" ? 90 : 180))) throw new Error("Coordinate is out of range."); const loc = d.locations[page * 25 + index]; loc[axis] = number; loc.coordinate_source = loc.lat === null || loc.lon === null ? "unresolved" : "manual" })} /></TableCell>)}<TableCell>{location.coordinate_source}</TableCell></TableRow>)}
      </TableBody></Table></div><div className="flex items-center gap-3"><Button variant="outline" disabled={!page} onClick={() => setPage(page - 1)}>Previous</Button><span className="text-sm">{count ? page * 25 + 1 : 0}–{Math.min((page + 1) * 25, count)} of {count}</span><Button variant="outline" disabled={(page + 1) * 25 >= count} onClick={() => setPage(page + 1)}>Next</Button></div>
      <details open><summary className="cursor-pointer font-medium">Run settings</summary><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([["trailer_capacity", "Trailer capacity (hundredths ft)"], ["max_leg_m", "Maximum leg (meters)"], ["k", "Clusters (blank = auto)"], ["kmeans_seed", "Cluster seed"], ["solver_seed", "Solver seed"], ["solver_time_limit_s", "Time per cluster (seconds)"], ["solver_max_iterations", "Iterations (blank = time limit)"], ["max_cluster_diameter_m", "Optional cluster diameter (meters; blank = off)"], ["travel_circuity", "Travel circuity"], ["cluster_circuity", "Cluster circuity"], ["cost_per_truck_cents", "Cost per truck (cents)"], ["cost_per_mile_cents", "Cost per mile (cents)"]] as [keyof ScenarioRunSettings, string][]).map(([name, label]) => <Field key={name} label={label}><Input type="number" min="0" step={name.includes("circuity") || name === "solver_time_limit_s" ? "any" : "1"} value={settings[name] == null ? "" : String(settings[name])} onChange={e => updateSetting(name, e.target.value === "" ? null : Number(e.target.value))} /></Field>)}</div>
        <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Objective"><select className="h-9 rounded-md border bg-background px-3" value={settings.objective} onChange={e => setSettings(previous => ({ ...previous, objective: e.target.value as ScenarioRunSettings["objective"] }))}><option value="trucks_then_distance">Fewest trucks, then miles</option><option value="weighted_distance">Fewest miles with truck penalty</option><option value="cost">Lowest cost</option></select></Field>{settings.objective === "weighted_distance" && <Field label="Truck penalty (meters)"><Input type="number" min="0" value={settings.weighted_truck_penalty_m ?? ""} onChange={e => updateSetting("weighted_truck_penalty_m", e.target.value === "" ? null : Number(e.target.value))} /></Field>}{(["missing_coordinates", "far_from_depot", "oversize_stop"] as const).map(check => <Field key={check} label={check.replaceAll("_", " ")}><select className="h-9 rounded-md border bg-background px-3" value={settings.preflight[check]} onChange={e => setSettings(previous => ({ ...previous, preflight: { ...previous.preflight, [check]: e.target.value as "block" | "warn" } }))}><option value="block">Block run</option><option value="warn">Warn only</option></select></Field>)}</div>
        <p className="mt-3 text-xs text-muted-foreground">Cost objective requires both rates. Cluster diameter is optional and off by default; maximum leg limits each drive. Run settings are saved with each run.</p>
      </details>
      <div className="flex flex-wrap gap-2"><Button disabled={busy || dirty || conflict || (settings.objective === "cost" && (settings.cost_per_truck_cents === null || settings.cost_per_mile_cents === null))} onClick={() => action(() => reviewAndRun())}>Review and run saved version</Button><Button variant="outline" disabled={busy || dirty || conflict} onClick={() => action(async () => { await preflight(); setMessage("Preflight review updated.") })}>Review checks</Button></div>
      {findings.length > 0 && <div className="space-y-3" aria-label="Preflight findings"><h3 className="font-medium">Preflight review</h3>{findings.map((finding, index) => <div key={`${finding.check}-${index}`} className="rounded-lg border p-3 text-sm"><p className="font-medium">{finding.check.replaceAll("_", " ")} · {finding.action === "block" ? "Blocks run" : "Warning"}</p><p className="mt-1 text-muted-foreground">{finding.message}</p><p className="mt-1 break-all text-xs text-muted-foreground">{finding.line_ids.length} affected lines{finding.line_ids.length ? `: ${finding.line_ids.slice(0, 30).join(", ")}${finding.line_ids.length > 30 ? "…" : ""}` : ""}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => { setTab(finding.check === "missing_coordinates" || finding.check === "approximate_coordinates" ? "locations" : "orders"); setPage(0); document.getElementById("scenario-data")?.scrollIntoView({ behavior: "smooth" }) }}>Edit data</Button>{finding.action === "block" && finding.line_ids.length > 0 && <Button size="sm" variant="outline" disabled={busy} onClick={() => action(async () => { const candidate = { ...settings, excluded_line_ids: [...new Set([...settings.excluded_line_ids, ...finding.line_ids])] }; setSettings(candidate); await reviewAndRun(candidate) })}>Exclude these lines and run</Button>}{finding.action === "block" && finding.check !== "approximate_coordinates" && <Button size="sm" variant="outline" onClick={() => { setSettings(previous => ({ ...previous, preflight: { ...previous.preflight, [finding.check]: "warn" } })); setFindings([]); setMessage("Policy changed to warn. Review checks again before running.") }}>Warn only</Button>}</div></div>)}</div>}
    </section>}
    <p role="status" aria-live="polite" className="whitespace-pre-wrap break-words text-sm">{busy ? "Working…" : message}</p>
  </div>
}
