/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Behavior */
        Behavior: {
            /**
             * Availability
             * @default implemented
             * @enum {string}
             */
            availability: "implemented" | "planned" | "unsupported";
            /** Description */
            description: string;
            /** Fixture */
            fixture: string | null;
            /** Id */
            id: string;
            /**
             * Provided By
             * @enum {string}
             */
            provided_by: "native" | "preprocessing" | "workaround" | "validation";
            /**
             * Restrictions
             * @default []
             */
            restrictions: string[];
        };
        /** Capabilities */
        Capabilities: {
            /**
             * Adapter Version
             * @default pyvrp-loads/1
             */
            adapter_version: string;
            /** Behaviors */
            behaviors: components["schemas"]["Behavior"][];
            defaults: components["schemas"]["Defaults"];
            limits: components["schemas"]["Limits"];
            /** Platform */
            platform: string;
            /** Python */
            python: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Travel Modes */
            travel_modes: string[];
            units: components["schemas"]["Units"];
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** ContractBundle */
        ContractBundle: {
            event: components["schemas"]["WorkerEvent"];
            manifest: components["schemas"]["StageManifest"];
            snapshot: components["schemas"]["Snapshot"];
        };
        /** Defaults */
        Defaults: {
            /**
             * Circuity
             * @default 1.2
             */
            circuity: number;
            /**
             * Max Cluster Diameter M
             * @default 804672
             */
            max_cluster_diameter_m: number;
            /**
             * Max Leg M
             * @default 804672
             */
            max_leg_m: number;
            /**
             * Trailer Capacity
             * @default 5300
             */
            trailer_capacity: number;
        };
        JsonValue: unknown;
        /** Lease */
        Lease: {
            /** Attempt */
            attempt: number;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Lease Token
             * Format: uuid
             */
            lease_token: string;
            /** Worker Id */
            worker_id: string;
        };
        /** Limits */
        Limits: {
            /**
             * Max Orders
             * @default 5000
             */
            max_orders: number;
            /**
             * Max Stops Per Solve
             * @default 500
             */
            max_stops_per_solve: number;
            /**
             * Run Wall Limit Seconds
             * @default 600
             */
            run_wall_limit_seconds: number;
            /**
             * Solve Attempt Limit Seconds
             * @default 300
             */
            solve_attempt_limit_seconds: number;
        };
        /** Snapshot */
        Snapshot: {
            /** Document */
            document: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** StageManifest */
        StageManifest: {
            /** Adapter Version */
            adapter_version: string;
            /** Created At Ms */
            created_at_ms: number;
            /** Effective Settings */
            effective_settings: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Input Hash */
            input_hash: string;
            /** Output Hash */
            output_hash: string;
            /** Parent Hashes */
            parent_hashes: string[];
            /** Producer Version */
            producer_version: string;
            /**
             * Reused From
             * @default null
             */
            reused_from: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Stage Type
             * @enum {string}
             */
            stage_type: "preflight" | "allocation" | "aggregation" | "clustering" | "travel" | "problem" | "solve" | "validation" | "summary";
        };
        /** Units */
        Units: {
            /**
             * Distance
             * @default meters (integer)
             */
            distance: string;
            /**
             * Linear Feet
             * @default hundredths of a foot (integer)
             */
            linear_feet: string;
            /**
             * Money
             * @default cents (integer)
             */
            money: string;
        };
        /** WorkerEvent */
        WorkerEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "progress" | "succeeded" | "failed" | "cancelled";
            lease: components["schemas"]["Lease"];
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Sequence */
            sequence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
