/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Evaluate
         * @description Manual plan evaluation (spec §10): bounded, synchronous CPU work in FastAPI's thread
         *     pool, never on the event loop. Only Next.js calls it, with the worker bearer token.
         */
        post: operations["post_evaluate_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllocationStageSummary */
        AllocationStageSummary: {
            /** Bound */
            bound: number | null;
            /**
             * Objective
             * @enum {string}
             */
            objective: "revenue_cents" | "priority_weighted_pieces";
            /** Runtime S */
            runtime_s: number;
            /**
             * Status
             * @enum {string}
             */
            status: "optimal" | "feasible" | "infeasible" | "model_invalid" | "unknown";
            /** Value */
            value: number;
        };
        /**
         * AllocationSummary
         * @description Strategy provenance (spec §8): heuristic or CP-SAT, with each CP-SAT stage's status.
         */
        AllocationSummary: {
            /**
             * Fulfillment Policy
             * @enum {string}
             */
            fulfillment_policy: "piece" | "whole_order";
            /**
             * Kind
             * @enum {string}
             */
            kind: "heuristic" | "cp_sat";
            /** Notes */
            notes: string[];
            /** Runtime S */
            runtime_s: number;
            /** Stages */
            stages: components["schemas"]["AllocationStageSummary"][];
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "order_date_then_value" | "first_come" | "priority" | "proportional" | "optimized";
        };
        /** Behavior */
        Behavior: {
            /**
             * Availability
             * @default implemented
             * @enum {string}
             */
            availability: "implemented" | "planned" | "unsupported";
            /** Description */
            description: string;
            /** Fixture */
            fixture: string | null;
            /** Id */
            id: string;
            /**
             * Provided By
             * @enum {string}
             */
            provided_by: "native" | "preprocessing" | "workaround" | "validation";
            /**
             * Restrictions
             * @default []
             */
            restrictions: string[];
        };
        /** Capabilities */
        Capabilities: {
            /**
             * Adapter Version
             * @default pyvrp-partition/1
             */
            adapter_version: string;
            /** Behaviors */
            behaviors: components["schemas"]["Behavior"][];
            defaults: components["schemas"]["Defaults"];
            limits: components["schemas"]["Limits"];
            /** Platform */
            platform: string;
            /** Python */
            python: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Travel Modes */
            travel_modes: string[];
            units: components["schemas"]["Units"];
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /**
         * ClockWindow
         * @description Service-start window in local clock time. `fold` picks the occurrence of an ambiguous
         *     (fall-back) time and applies to both ends. earliest > latest is a preflight finding.
         */
        ClockWindow: {
            /** Earliest */
            earliest: string;
            /**
             * Fold
             * @default null
             */
            fold: (0 | 1) | null;
            /** Latest */
            latest: string;
        };
        /**
         * ClusterPlan
         * @description Ordered visit IDs per truck for one cluster; the shape of a solve artifact's routes.
         */
        ClusterPlan: {
            /** Cluster Id */
            cluster_id: string;
            /** Routes */
            routes: string[][];
            /** Vehicle Types */
            vehicle_types?: string[] | null;
        };
        /** ClusterSummary */
        ClusterSummary: {
            /** Avg Fill */
            avg_fill: number | null;
            /** Capacity Lower Bound */
            capacity_lower_bound: number;
            /** Diameter M */
            diameter_m: number;
            /** Distance Bound M */
            distance_bound_m: number | null;
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Iterations */
            iterations: number;
            /** Load */
            load: number;
            /** Loaded Distance M */
            loaded_distance_m: number;
            /** Location Ids */
            location_ids: string[];
            /** Mean Centroid Distance M */
            mean_centroid_distance_m: number;
            /** Min Fill */
            min_fill: number | null;
            /** Objective Mode */
            objective_mode: string;
            /** Planned Amount Cents */
            planned_amount_cents: number;
            /** Planned Visit Count */
            planned_visit_count: number;
            /** Runtime S */
            runtime_s: number;
            /** Solver Feasible */
            solver_feasible: boolean | null;
            /**
             * Status
             * @enum {string}
             */
            status: "validated" | "invalid_candidate" | "no_candidate" | "nothing_to_solve";
            /** Truck Penalty */
            truck_penalty: number;
            /** Trucks */
            trucks: number;
            /** Violations */
            violations: string[];
            /** Visit Count */
            visit_count: number;
            warm_start?: components["schemas"]["ClusterWarmStart"] | null;
        };
        /**
         * ClusterWarmStart
         * @description One cluster's warm-start outcome. `initial_cost` is PyVRP's objective of the mapped plan on
         *     this run's problem; `final_cost` is the objective PyVRP returned starting from it (never higher
         *     with a feasible start: tests/test_warm_start.py).
         */
        ClusterWarmStart: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Final Cost
             * @default null
             */
            final_cost: number | null;
            /**
             * Initial Cost
             * @default null
             */
            initial_cost: number | null;
            /**
             * Reason
             * @default null
             */
            reason: ("travel_changed" | "visit_set_changed" | "demand_changed" | "source_invalid" | "invalid_on_new_problem" | "solver_rejected" | "fleet_changed") | null;
            /**
             * Source Cluster Id
             * @default null
             */
            source_cluster_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "used" | "skipped";
        };
        /** ClusteringSummary */
        ClusteringSummary: {
            /** Auto Limit Reached */
            auto_limit_reached: boolean;
            /** Effective Cluster Count */
            effective_cluster_count: number;
            /** Fits */
            fits: number;
            /**
             * H3 Resolution
             * @default null
             */
            h3_resolution: number | null;
            /** Raw Cluster Count */
            raw_cluster_count: number;
            /** Repairs */
            repairs: components["schemas"]["Repair"][];
            /** Requested K */
            requested_k: number | null;
            /** Selected K */
            selected_k: number | null;
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "kmeans" | "h3" | "none";
        };
        /** ContractBundle */
        ContractBundle: {
            event: components["schemas"]["WorkerEvent"];
            manifest: components["schemas"]["StageManifest"];
            snapshot: components["schemas"]["Snapshot"];
        };
        /**
         * CoordinateOrigin
         * @description A location's first coordinate, kept with its provenance when a manual correction or an
         *     explicit re-geocode replaces it (spec §6: keep original and corrected provenance).
         */
        CoordinateOrigin: {
            /**
             * Coordinate Source
             * @enum {string}
             */
            coordinate_source: "imported" | "manual" | "census" | "zcta" | "unresolved";
            /** @default null */
            geocode: components["schemas"]["GeocodeMatch"] | null;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
        };
        /** Defaults */
        Defaults: {
            /**
             * Circuity
             * @default 1.2
             */
            circuity: number;
            /** Max Cluster Diameter M */
            max_cluster_diameter_m?: number | null;
            /**
             * Max Leg M
             * @default 804672
             */
            max_leg_m: number;
            /**
             * Trailer Capacity
             * @default 5300
             */
            trailer_capacity: number;
        };
        /** Depot */
        Depot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** Diagnostic */
        Diagnostic: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
        };
        /**
         * EvaluateRequest
         * @description One cluster of a completed run, as its artifacts recorded it, plus the plans to evaluate.
         *
         *     ``cluster``, ``problem`` and ``travel`` are that cluster's entries of the clustering, problem
         *     and (decoded) travel artifacts; ``visits`` are the aggregation's visits of the cluster.
         *     ``reference`` is normally the run's optimized routes, evaluated alongside for comparison.
         */
        EvaluateRequest: {
            /** Cluster */
            cluster: {
                [key: string]: unknown;
            };
            plan: components["schemas"]["ClusterPlan"];
            /** Problem */
            problem: {
                [key: string]: unknown;
            };
            reference?: components["schemas"]["ClusterPlan"] | null;
            scenario: components["schemas"]["ScenarioDocument"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            settings: components["schemas"]["RunSettings"];
            /** Travel */
            travel: {
                [key: string]: unknown;
            };
            /** Travel Snapshot */
            travel_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Visits */
            visits: {
                [key: string]: unknown;
            }[];
        };
        /** EvaluateResponse */
        EvaluateResponse: {
            /** Cluster Id */
            cluster_id: string;
            /**
             * Evaluator Version
             * @default fillrate-evaluate/1
             */
            evaluator_version: string;
            manual: components["schemas"]["PlanEvaluation"];
            reference?: components["schemas"]["PlanEvaluation"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** ExplorerH3 */
        ExplorerH3: {
            /** Diameter Repairs */
            diameter_repairs: number;
            /** Effective Cluster Count */
            effective_cluster_count: number;
            /** Inertia */
            inertia: number;
            /** Raw Cluster Count */
            raw_cluster_count: number;
            /** Resolution */
            resolution: number;
            /**
             * Stability
             * @default deterministic
             * @constant
             */
            stability: "deterministic";
        };
        /** ExplorerK */
        ExplorerK: {
            /** Diameter Repairs By Seed */
            diameter_repairs_by_seed: number[];
            /** Effective Cluster Count */
            effective_cluster_count: number;
            /** Inertia By Seed */
            inertia_by_seed: number[];
            /** Inertia Mean */
            inertia_mean: number;
            /** K */
            k: number;
            /** Raw Cluster Count */
            raw_cluster_count: number;
            /** Stability Raw */
            stability_raw: number | null;
            /** Stability Repaired */
            stability_repaired: number | null;
        };
        /** ExplorerLocation */
        ExplorerLocation: {
            /** Agreement Raw */
            agreement_raw: number | null;
            /** Agreement Repaired */
            agreement_repaired: number | null;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Reference Cluster */
            reference_cluster: number;
        };
        /**
         * ExplorerSettings
         * @description A clustering-only job: no allocation changes, no PyVRP. `base` supplies the population
         *     (eligible, allocated locations) and the spatial policy; ks × seeds are the k-means tasks and
         *     each H3 resolution is one deterministic task. All of them count toward the task cap.
         */
        ExplorerSettings: {
            base?: components["schemas"]["RunSettings"];
            /** H3 Resolutions */
            h3_resolutions?: number[];
            /**
             * Kind
             * @default explorer
             * @constant
             */
            kind: "explorer";
            /**
             * Ks
             * @default null
             */
            ks: number[] | null;
            /**
             * Reference Seed
             * @default 0
             */
            reference_seed: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Seeds */
            seeds?: number[];
            /**
             * Selected K
             * @default null
             */
            selected_k: number | null;
        };
        /** ExplorerSummary */
        ExplorerSummary: {
            depot: components["schemas"]["Depot"];
            /** Fits */
            fits: number;
            /** H3 */
            h3: components["schemas"]["ExplorerH3"][];
            /**
             * Kind
             * @default explorer
             * @constant
             */
            kind: "explorer";
            /** Ks */
            ks: number[];
            /** Locations */
            locations: components["schemas"]["ExplorerLocation"][];
            /** Locations Clustered */
            locations_clustered: number;
            /** Max Tasks */
            max_tasks: number;
            /** Per K */
            per_k: components["schemas"]["ExplorerK"][];
            /** Reference Seed */
            reference_seed: number;
            /** Scenario Name */
            scenario_name: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Seeds */
            seeds: number[];
            /** Selected K */
            selected_k: number;
            settings: components["schemas"]["ExplorerSettings"];
            /** Tasks */
            tasks: number;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /**
         * FleetTypeUse
         * @description What a fleet run used of one vehicle type, fleet-wide (all clusters).
         */
        FleetTypeUse: {
            /** Avg Fill */
            avg_fill: number | null;
            /** Capacity */
            capacity: number;
            /** Count */
            count: number | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Load */
            load: number;
            /** Min Fill */
            min_fill: number | null;
            /** Trucks */
            trucks: number;
        };
        /**
         * FleetVehicleType
         * @description One vehicle type of an optional heterogeneous fleet (spec §3, M6).
         *
         *     `count` is the number of vehicles of this type available to the whole dispatch (all clusters
         *     together); null means unlimited, which is how the single trailer behaves today. `capacity` is
         *     in the pipeline's capacity unit, integer hundredths of a foot. The two rates are used only by
         *     the `cost` objective, which requires them on every type.
         */
        FleetVehicleType: {
            /** Capacity */
            capacity: number;
            /**
             * Count
             * @default null
             */
            count: number | null;
            /**
             * Fixed Cost Cents
             * @default null
             */
            fixed_cost_cents: number | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Per Mile Cents
             * @default null
             */
            per_mile_cents: number | null;
        };
        /**
         * GeocodeMatch
         * @description How an address became a coordinate (spec §6). Records the match, never a confidence score.
         *
         *     Census matches are interpolated along address ranges, not rooftop points. ZCTA matches are
         *     the Gazetteer internal point of the ZIP Code Tabulation Area with the same code as the ZIP.
         */
        GeocodeMatch: {
            /** Dataset */
            dataset: string;
            /**
             * Match Type
             * @default null
             */
            match_type: ("exact" | "non_exact") | null;
            /**
             * Matched Address
             * @default null
             */
            matched_address: string | null;
            /**
             * Provider
             * @enum {string}
             */
            provider: "census" | "zcta";
            /** Resolved At */
            resolved_at: string;
            /**
             * Response Ref
             * @default null
             */
            response_ref: string | null;
            /**
             * Zcta
             * @default null
             */
            zcta: string | null;
        };
        /** InventoryItem */
        InventoryItem: {
            /** Available Pieces */
            available_pieces: number;
            /** Product Id */
            product_id: string;
        };
        JsonValue: unknown;
        /**
         * LabClient
         * @description A visit created directly (spec §5: no order needed). Delivery is per dimension id; a
         *     dimension left out delivers 0.
         */
        LabClient: {
            /** Delivery */
            delivery?: {
                [key: string]: number;
            };
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Lat
             * @default null
             */
            lat: number | null;
            /**
             * Lon
             * @default null
             */
            lon: number | null;
            /**
             * Service Duration
             * @default 0
             */
            service_duration: number;
            /**
             * X
             * @default null
             */
            x: number | null;
            /**
             * Y
             * @default null
             */
            y: number | null;
        };
        /** LabDepot */
        LabDepot: {
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Lat
             * @default null
             */
            lat: number | null;
            /**
             * Lon
             * @default null
             */
            lon: number | null;
            /**
             * X
             * @default null
             */
            x: number | null;
            /**
             * Y
             * @default null
             */
            y: number | null;
        };
        /**
         * LabDimension
         * @description A named load dimension (units, weight, volume or any user-defined resource).
         */
        LabDimension: {
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Unit */
            unit: string;
        };
        /** LabFleetUse */
        LabFleetUse: {
            /** Available */
            available: number;
            /** Used */
            used: number;
            /** Vehicle Type */
            vehicle_type: string;
        };
        /** LabInstance */
        LabInstance: {
            /** Clients */
            clients: components["schemas"]["LabClient"][];
            /**
             * Coordinates
             * @enum {string}
             */
            coordinates: "planar" | "geographic";
            /**
             * Cost Unit
             * @default cost units
             */
            cost_unit: string;
            /** Depots */
            depots: components["schemas"]["LabDepot"][];
            /**
             * Description
             * @default
             */
            description: string;
            /** Dimensions */
            dimensions: components["schemas"]["LabDimension"][];
            /**
             * Kind
             * @default lab_instance
             * @constant
             */
            kind: "lab_instance";
            /** Name */
            name: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            solver?: components["schemas"]["LabSolver"];
            travel?: components["schemas"]["LabTravel"];
            /** Vehicle Types */
            vehicle_types: components["schemas"]["LabVehicleType"][];
        };
        /**
         * LabObjective
         * @description Nominal objective recomputed from the instance (PyVRP 0.14 semantics): per used vehicle
         *     its fixed cost, plus unit_distance_cost × route distance and unit_duration_cost × route
         *     duration. Infeasibility penalties are never part of it.
         */
        LabObjective: {
            /** Distance Cost */
            distance_cost: number;
            /** Duration Cost */
            duration_cost: number;
            /** Fixed Cost */
            fixed_cost: number;
            /** Total */
            total: number;
        };
        /** LabResult */
        LabResult: {
            /**
             * Coordinates
             * @enum {string}
             */
            coordinates: "planar" | "geographic";
            /** Fleet */
            fleet: components["schemas"]["LabFleetUse"][];
            /** Instance Name */
            instance_name: string;
            /**
             * Kind
             * @default lab_result
             * @constant
             */
            kind: "lab_result";
            objective: components["schemas"]["LabObjective"];
            /** Problem Fingerprint */
            problem_fingerprint: string;
            /**
             * Proof
             * @default heuristic
             * @constant
             */
            proof: "heuristic";
            /** Routes */
            routes: components["schemas"]["LabRoute"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            solver: components["schemas"]["LabSolverInfo"];
            /** Solver Feasible */
            solver_feasible: boolean;
            totals: components["schemas"]["LabTotals"];
            units: components["schemas"]["LabUnits"];
            /** Validated Feasible */
            validated_feasible: boolean;
            /** Violations */
            violations: components["schemas"]["LabViolation"][];
        };
        /** LabRoute */
        LabRoute: {
            /** Cost */
            cost: number;
            /** Distance */
            distance: number;
            /** Distance Cost */
            distance_cost: number;
            /** Duration */
            duration: number;
            /** Duration Cost */
            duration_cost: number;
            /** Fixed Cost */
            fixed_cost: number;
            /** Index */
            index: number;
            /** Load */
            load: {
                [key: string]: number;
            };
            /** Service Duration */
            service_duration: number;
            /** Travel Duration */
            travel_duration: number;
            /** Utilization */
            utilization: {
                [key: string]: number;
            };
            /** Vehicle Type */
            vehicle_type: string;
            /** Visits */
            visits: components["schemas"]["LabVisit"][];
        };
        /**
         * LabSolver
         * @description Seed and stopping criteria. With ``max_iterations`` the run stops after that many
         *     iterations (reproducible across machines) unless the runtime cap is hit first; without it,
         *     the runtime alone stops the search (machine dependent).
         */
        LabSolver: {
            /**
             * Max Iterations
             * @default 2000
             */
            max_iterations: number | null;
            /**
             * Max Runtime S
             * @default 30
             */
            max_runtime_s: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** LabSolverInfo */
        LabSolverInfo: {
            /** Adapter Version */
            adapter_version: string;
            /** Excess Distance */
            excess_distance: number;
            /** Excess Load */
            excess_load: {
                [key: string]: number;
            };
            /** Iterations */
            iterations: number;
            /** Max Iterations */
            max_iterations: number | null;
            /** Max Runtime S */
            max_runtime_s: number;
            /**
             * Name
             * @default pyvrp
             * @constant
             */
            name: "pyvrp";
            /** Nominal Cost */
            nominal_cost: number;
            /** Runtime S */
            runtime_s: number;
            /** Seed */
            seed: number;
            /**
             * Stopped By
             * @enum {string}
             */
            stopped_by: "iterations" | "runtime";
            /** Time Warp */
            time_warp: number;
            /** Version */
            version: string;
        };
        /** LabTotals */
        LabTotals: {
            /** Clients Served */
            clients_served: number;
            /** Clients Total */
            clients_total: number;
            /** Distance */
            distance: number;
            /** Duration */
            duration: number;
            /** Load */
            load: {
                [key: string]: number;
            };
            /** Routes */
            routes: number;
            /** Service Duration */
            service_duration: number;
            /** Travel Duration */
            travel_duration: number;
        };
        /**
         * LabTravel
         * @description Geographic only: haversine × circuity meters, and seconds at a constant speed.
         */
        LabTravel: {
            /**
             * Circuity
             * @default 1.2
             */
            circuity: number;
            /**
             * Speed M Per S
             * @default 11.176
             */
            speed_m_per_s: number;
        };
        /** LabUnits */
        LabUnits: {
            /** Cost */
            cost: string;
            /** Dimensions */
            dimensions: {
                [key: string]: string;
            };
            /** Distance */
            distance: string;
            /** Duration */
            duration: string;
        };
        /**
         * LabVehicleType
         * @description A vehicle type with a finite count. Every vehicle starts and ends at the single depot
         *     (closed routes; PyVRP-native, no open-route workaround). Capacity names every dimension.
         */
        LabVehicleType: {
            /** Capacity */
            capacity: {
                [key: string]: number;
            };
            /** Count */
            count: number;
            /**
             * Fixed Cost
             * @default 0
             */
            fixed_cost: number;
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Max Distance
             * @default null
             */
            max_distance: number | null;
            /**
             * Shift Duration
             * @default null
             */
            shift_duration: number | null;
            /**
             * Unit Distance Cost
             * @default 1
             */
            unit_distance_cost: number;
            /**
             * Unit Duration Cost
             * @default 0
             */
            unit_duration_cost: number;
        };
        /** LabViolation */
        LabViolation: {
            /**
             * Client Id
             * @default null
             */
            client_id: string | null;
            /** Code */
            code: string;
            /**
             * Dimension
             * @default null
             */
            dimension: string | null;
            /** Message */
            message: string;
            /**
             * Route
             * @default null
             */
            route: number | null;
            /**
             * Vehicle Type
             * @default null
             */
            vehicle_type: string | null;
        };
        /** LabVisit */
        LabVisit: {
            /** Arrival */
            arrival: number;
            /** Client Id */
            client_id: string;
            /** Departure */
            departure: number;
            /** Leg Distance */
            leg_distance: number;
            /** Leg Duration */
            leg_duration: number;
            /** Load After */
            load_after: {
                [key: string]: number;
            };
            /** Load Before */
            load_before: {
                [key: string]: number;
            };
            /** Service Duration */
            service_duration: number;
        };
        /** Lease */
        Lease: {
            /** Attempt */
            attempt: number;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Lease Token
             * Format: uuid
             */
            lease_token: string;
            /** Worker Id */
            worker_id: string;
        };
        /** Limits */
        Limits: {
            /**
             * Max Orders
             * @default 5000
             */
            max_orders: number;
            /**
             * Max Stops Per Solve
             * @default 500
             */
            max_stops_per_solve: number;
            /**
             * Run Wall Limit Seconds
             * @default 600
             */
            run_wall_limit_seconds: number;
            /**
             * Solve Attempt Limit Seconds
             * @default 300
             */
            solve_attempt_limit_seconds: number;
        };
        /** LineOnBoard */
        LineOnBoard: {
            /** Amount Cents */
            amount_cents: number;
            /** Line Id */
            line_id: string;
            /** Linear Feet */
            linear_feet: number;
            /** Order Id */
            order_id: string;
            /** Pieces */
            pieces: number;
            /** Product Id */
            product_id: string;
        };
        /** Location */
        Location: {
            /**
             * Address
             * @default null
             */
            address: string | null;
            /**
             * Coordinate Source
             * @enum {string}
             */
            coordinate_source: "imported" | "manual" | "census" | "zcta" | "unresolved";
            /** @default null */
            geocode: components["schemas"]["GeocodeMatch"] | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** @default null */
            original: components["schemas"]["CoordinateOrigin"] | null;
            /** Service Minutes */
            service_minutes?: number | null;
            window?: components["schemas"]["ClockWindow"] | null;
        };
        /** MapLocation */
        MapLocation: {
            /** Cluster Id */
            cluster_id: string | null;
            /**
             * Coordinate Source
             * @enum {string}
             */
            coordinate_source: "imported" | "manual" | "census" | "zcta" | "unresolved";
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "planned" | "partial" | "unplanned" | "excluded" | "no_demand";
        };
        /** Order */
        Order: {
            /**
             * Customer Id
             * @default null
             */
            customer_id: string | null;
            /** Id */
            id: string;
            /** Lines */
            lines: components["schemas"]["OrderLine"][];
            /** Location Id */
            location_id: string;
            /** Order Date */
            order_date: string;
            /**
             * Priority
             * @default 1
             */
            priority: number;
        };
        /** OrderLine */
        OrderLine: {
            /** Id */
            id: string;
            /**
             * Linear Feet Per Piece
             * @default null
             */
            linear_feet_per_piece: number | null;
            /** Net Value Per Piece Cents */
            net_value_per_piece_cents: number;
            /** Ordered Pieces */
            ordered_pieces: number;
            /** Product Id */
            product_id: string;
        };
        /** PlanEvaluation */
        PlanEvaluation: {
            metrics: components["schemas"]["PlanMetrics"];
            /** Trucks */
            trucks: components["schemas"]["TruckSummary"][];
            /** Valid */
            valid: boolean;
            /** Violations */
            violations: components["schemas"]["PlanViolation"][];
        };
        /**
         * PlanMetrics
         * @description The run's cluster metrics for this plan, under the run's objective definition.
         */
        PlanMetrics: {
            /** Avg Fill */
            avg_fill: number | null;
            /** Capacity Lower Bound */
            capacity_lower_bound: number;
            /** Distance Cost */
            distance_cost: number;
            /** Drive S */
            drive_s: number | null;
            /** Load */
            load: number;
            /** Loaded Distance M */
            loaded_distance_m: number | null;
            /** Min Fill */
            min_fill: number | null;
            /** Objective */
            objective: number | null;
            /** Objective Cents */
            objective_cents?: number | null;
            /** Objective Mode */
            objective_mode: string;
            /** Planned Amount Cents */
            planned_amount_cents: number;
            /** Planned Visit Count */
            planned_visit_count: number;
            /** Truck Penalty */
            truck_penalty: number;
            /** Trucks */
            trucks: number;
            /**
             * Unmeasured Trucks
             * @default 0
             */
            unmeasured_trucks: number;
            /** Visit Count */
            visit_count: number;
            /** Wait S */
            wait_s: number | null;
        };
        /** PlanViolation */
        PlanViolation: {
            /**
             * Code
             * @enum {string}
             */
            code: "unknown_visit" | "unreachable_visit" | "duplicate_visit" | "missing_visit" | "empty_truck" | "over_capacity" | "leg_missing" | "leg_over_limit" | "leg_mismatch" | "leg_no_duration" | "window_late" | "horizon_exceeded" | "cluster_diameter" | "vehicle_type_missing" | "unknown_vehicle_type" | "fleet_count_exceeded";
            /** Message */
            message: string;
            /** Truck */
            truck?: number | null;
            /** Visit Id */
            visit_id?: string | null;
        };
        /**
         * PreflightFinding
         * @description One preflight check that found something. `action` is what the run did about it.
         */
        PreflightFinding: {
            /**
             * Action
             * @enum {string}
             */
            action: "block" | "warn";
            /**
             * Check
             * @enum {string}
             */
            check: "missing_coordinates" | "far_from_depot" | "oversize_stop" | "far_via_stop" | "approximate_coordinates" | "window_empty" | "window_unreachable";
            /** Line Ids */
            line_ids: string[];
            /** Location Ids */
            location_ids: string[];
            /** Message */
            message: string;
        };
        /**
         * PreflightPolicy
         * @description M2 scope item 8: which preflight checks stop a run. Policy, not physics (§7).
         *
         *     Round two (spec v1.9): `far_from_depot` covers only stops no chain of allowed drives
         *     reaches; a far stop reachable through another stop is the warning `far_via_stop`. A stop
         *     larger than one trailer splits across shipments by default.
         */
        PreflightPolicy: {
            /**
             * Approximate Coordinates
             * @default warn
             * @enum {string}
             */
            approximate_coordinates: "block" | "warn";
            /**
             * Far From Depot
             * @default block
             * @enum {string}
             */
            far_from_depot: "block" | "warn";
            /**
             * Missing Coordinates
             * @default block
             * @enum {string}
             */
            missing_coordinates: "block" | "warn";
            /**
             * Oversize Stop
             * @default warn
             * @enum {string}
             */
            oversize_stop: "block" | "warn";
        };
        /** Product */
        Product: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Linear Feet Per Piece */
            linear_feet_per_piece: number;
        };
        /** ProductReconciliation */
        ProductReconciliation: {
            /** Allocated */
            allocated: number;
            /** Allocated Cents */
            allocated_cents: number;
            /** Allocated Unplanned */
            allocated_unplanned: number;
            /** Eligible */
            eligible: number;
            /** Excluded */
            excluded: number;
            /** Label */
            label: string;
            /** Ordered */
            ordered: number;
            /** Ordered Cents */
            ordered_cents: number;
            /** Planned */
            planned: number;
            /** Planned Cents */
            planned_cents: number;
            /** Product Id */
            product_id: string;
            /** Residual */
            residual: number;
            /** Starting Inventory */
            starting_inventory: number;
            /** Unselected */
            unselected: number;
        };
        /** Repair */
        Repair: {
            /** Detail */
            detail: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "diameter" | "solve_size" | "degenerate_size";
        };
        /** RunSettings */
        RunSettings: {
            /**
             * Allocation Objective
             * @default revenue
             * @enum {string}
             */
            allocation_objective: "revenue" | "priority_then_revenue";
            /**
             * Allocation Strategy
             * @default order_date_then_value
             * @enum {string}
             */
            allocation_strategy: "order_date_then_value" | "first_come" | "priority" | "proportional" | "optimized";
            /**
             * Allocation Time Limit S
             * @default 10
             */
            allocation_time_limit_s: number;
            /**
             * Auto K Cap
             * @default 25
             */
            auto_k_cap: number;
            /**
             * Cluster Circuity
             * @default 1.2
             */
            cluster_circuity: number;
            /**
             * Cluster Strategy
             * @default kmeans
             * @enum {string}
             */
            cluster_strategy: "kmeans" | "h3" | "none";
            /**
             * Cost Per Mile Cents
             * @default null
             */
            cost_per_mile_cents: number | null;
            /**
             * Cost Per Truck Cents
             * @default null
             */
            cost_per_truck_cents: number | null;
            /** Excluded Line Ids */
            excluded_line_ids?: string[];
            /** Fleet */
            fleet?: components["schemas"]["FleetVehicleType"][] | null;
            /**
             * Fulfillment Policy
             * @default piece
             * @enum {string}
             */
            fulfillment_policy: "piece" | "whole_order";
            /**
             * H3 Resolution
             * @default 2
             */
            h3_resolution: number;
            /**
             * Inventory Percent
             * @default 100
             */
            inventory_percent: number;
            /**
             * K
             * @default null
             */
            k: number | null;
            /**
             * Kmeans N Init
             * @default 10
             */
            kmeans_n_init: number;
            /**
             * Kmeans Seed
             * @default 0
             */
            kmeans_seed: number;
            /**
             * Max Cluster Diameter M
             * @default null
             */
            max_cluster_diameter_m: number | null;
            /**
             * Max Leg M
             * @default 804672
             */
            max_leg_m: number;
            /**
             * Max Stops
             * @default 500
             */
            max_stops: number;
            /**
             * Objective
             * @default trucks_then_distance
             * @enum {string}
             */
            objective: "trucks_then_distance" | "weighted_distance" | "cost";
            preflight?: components["schemas"]["PreflightPolicy"];
            /**
             * Respect Order Date
             * @default false
             */
            respect_order_date: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Solver Max Iterations
             * @default null
             */
            solver_max_iterations: number | null;
            /**
             * Solver Seed
             * @default 0
             */
            solver_seed: number;
            /**
             * Solver Time Limit S
             * @default 10
             */
            solver_time_limit_s: number;
            /**
             * Trailer Capacity
             * @default 5300
             */
            trailer_capacity: number;
            /**
             * Travel Circuity
             * @default 1.2
             */
            travel_circuity: number;
            /**
             * Travel Snapshot Id
             * @default null
             */
            travel_snapshot_id: string | null;
            warm_start?: components["schemas"]["WarmStartSource"] | null;
            /**
             * Weighted Truck Penalty M
             * @default null
             */
            weighted_truck_penalty_m: number | null;
        };
        /** RunSummary */
        RunSummary: {
            /** @default null */
            allocation: components["schemas"]["AllocationSummary"] | null;
            clustering: components["schemas"]["ClusteringSummary"];
            /** Clusters */
            clusters: components["schemas"]["ClusterSummary"][];
            /**
             * Coverage
             * @enum {string}
             */
            coverage: "complete" | "partial" | "empty";
            depot: components["schemas"]["Depot"];
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Fleet Usage */
            fleet_usage?: components["schemas"]["FleetTypeUse"][] | null;
            /** Locations */
            locations: components["schemas"]["MapLocation"][];
            /** Preflight */
            preflight?: components["schemas"]["PreflightFinding"][];
            /** Products */
            products: components["schemas"]["ProductReconciliation"][];
            /**
             * Proof
             * @default heuristic
             * @constant
             */
            proof: "heuristic";
            /** Scenario Name */
            scenario_name: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            settings: components["schemas"]["RunSettings"];
            time?: components["schemas"]["TimeSummary"] | null;
            totals: components["schemas"]["Totals"];
            /** @default null */
            travel: components["schemas"]["TravelSummary"] | null;
            /** Trucks */
            trucks: components["schemas"]["TruckSummary"][];
            /** Unplanned */
            unplanned: components["schemas"]["UnplannedLine"][];
            /**
             * Validity
             * @enum {string}
             */
            validity: "valid" | "invalid";
            /** Versions */
            versions: {
                [key: string]: string;
            };
            warm_start?: components["schemas"]["WarmStartSummary"] | null;
        };
        /** ScenarioDocument */
        ScenarioDocument: {
            depot: components["schemas"]["Depot"];
            /** Inventory */
            inventory: components["schemas"]["InventoryItem"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Name */
            name: string;
            /** Orders */
            orders: components["schemas"]["Order"][];
            /** Products */
            products: components["schemas"]["Product"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            time_model?: components["schemas"]["TimeModel"] | null;
        };
        /** Snapshot */
        Snapshot: {
            /** Document */
            document: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** StageManifest */
        StageManifest: {
            /** Adapter Version */
            adapter_version: string;
            /** Created At Ms */
            created_at_ms: number;
            /** Effective Settings */
            effective_settings: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Input Hash */
            input_hash: string;
            /** Output Hash */
            output_hash: string;
            /** Parent Hashes */
            parent_hashes: string[];
            /** Producer Version */
            producer_version: string;
            /**
             * Reused From
             * @default null
             */
            reused_from: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Stage Type
             * @enum {string}
             */
            stage_type: "preflight" | "allocation" | "aggregation" | "clustering" | "travel" | "problem" | "warm_start" | "solve" | "validation" | "summary" | "explorer" | "lab";
        };
        /**
         * TimeModel
         * @description Single-day time model (spec §5): clock strings are local to `timezone` on `planning_date`
         *     and normalize to elapsed integer seconds from local midnight. `horizon_end` may pass 24:00
         *     (late shifts), at most 48:00. `depot_open` is when trucks leave the depot.
         */
        TimeModel: {
            /**
             * Depot Open
             * @default 00:00
             */
            depot_open: string;
            /**
             * Horizon End
             * @default 24:00
             */
            horizon_end: string;
            /** Planning Date */
            planning_date: string;
            /** Timezone */
            timezone: string;
        };
        /**
         * TimeSummary
         * @description The time model a time-window run used; `*_s` values are seconds from local midnight.
         */
        TimeSummary: {
            /** Depot Open S */
            depot_open_s: number;
            /** Horizon End S */
            horizon_end_s: number;
            /** Midnight Epoch S */
            midnight_epoch_s: number;
            /** Planning Date */
            planning_date: string;
            /** Timezone */
            timezone: string;
        };
        /** Totals */
        Totals: {
            /** Allocated Cents */
            allocated_cents: number;
            /** Avg Fill */
            avg_fill: number | null;
            /** Capacity Lower Bound */
            capacity_lower_bound: number;
            /** Load */
            load: number;
            /** Loaded Distance M */
            loaded_distance_m: number;
            /** Locations */
            locations: number;
            /** Min Fill */
            min_fill: number | null;
            /** Ordered Cents */
            ordered_cents: number;
            /** Planned Cents */
            planned_cents: number;
            /** Planned Visits */
            planned_visits: number;
            /** Sum Cluster Lower Bounds */
            sum_cluster_lower_bounds: number;
            /** Trucks */
            trucks: number;
            /** Utilization */
            utilization: number | null;
            /** Visits */
            visits: number;
        };
        /**
         * TravelSummary
         * @description Which travel data the run used (spec §7): estimated, or a stored directed snapshot.
         */
        TravelSummary: {
            /**
             * Circuity
             * @default null
             */
            circuity: number | null;
            /** Dataset Revision */
            dataset_revision: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "estimated" | "snapshot";
            /**
             * Node Count
             * @default null
             */
            node_count: number | null;
            /** Profile */
            profile: string;
            /** Provider */
            provider: string;
            /** Provider Version */
            provider_version: string;
            /**
             * Snapshot Id
             * @default null
             */
            snapshot_id: string | null;
            /**
             * Warning Count
             * @default null
             */
            warning_count: number | null;
        };
        /** TruckSummary */
        TruckSummary: {
            /** Amount Cents */
            amount_cents: number;
            /** Cluster Id */
            cluster_id: string;
            /** Distance M */
            distance_m: number;
            /**
             * Drive S
             * @default null
             */
            drive_s: number | null;
            /** End S */
            end_s?: number | null;
            /** Fill */
            fill: number;
            /** Id */
            id: string;
            /** Load */
            load: number;
            /** Service S Total */
            service_s_total?: number | null;
            /** Shift Start S */
            shift_start_s?: number | null;
            /** Vehicle Type Id */
            vehicle_type_id?: string | null;
            /** Visits */
            visits: components["schemas"]["TruckVisit"][];
            /** Wait S Total */
            wait_s_total?: number | null;
        };
        /** TruckVisit */
        TruckVisit: {
            /** Arrival S */
            arrival_s?: number | null;
            /** Departure S */
            departure_s?: number | null;
            /** Leg M */
            leg_m: number;
            /**
             * Leg S
             * @default null
             */
            leg_s: number | null;
            /** Lines */
            lines: components["schemas"]["LineOnBoard"][];
            /** Load */
            load: number;
            /** Location Id */
            location_id: string;
            /** Sequence */
            sequence: number;
            /** Service S */
            service_s?: number | null;
            /** Start S */
            start_s?: number | null;
            /** Visit Id */
            visit_id: string;
            /** Wait S */
            wait_s?: number | null;
            /** Window Earliest S */
            window_earliest_s?: number | null;
            /** Window Latest S */
            window_latest_s?: number | null;
        };
        /** Units */
        Units: {
            /**
             * Distance
             * @default meters (integer)
             */
            distance: string;
            /**
             * Linear Feet
             * @default hundredths of a foot (integer)
             */
            linear_feet: string;
            /**
             * Money
             * @default cents (integer)
             */
            money: string;
        };
        /** UnplannedLine */
        UnplannedLine: {
            /** Amount Cents */
            amount_cents: number;
            /** Evidence */
            evidence: string;
            /** Line Id */
            line_id: string;
            /** Location Id */
            location_id: string;
            /** Order Id */
            order_id: string;
            /** Pieces */
            pieces: number;
            /** Product Id */
            product_id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "excluded_unresolved_coordinates" | "excluded_by_user" | "excluded_with_order" | "oversize_piece" | "stock_shortage" | "unreachable" | "unreachable_in_partition" | "candidate_invalid" | "no_valid_candidate";
            /**
             * Stage
             * @enum {string}
             */
            stage: "preflight" | "allocation" | "problem" | "solve" | "validation";
        };
        /**
         * WarmStartCluster
         * @description A source cluster: validated ones carry their routes in service order; others carry none.
         *     Fleet plans also carry each route's vehicle type ID, parallel to `routes`.
         */
        WarmStartCluster: {
            /** Cluster Id */
            cluster_id: string;
            /** Location Ids */
            location_ids: string[];
            /** Routes */
            routes: components["schemas"]["WarmStartVisit"][][];
            /**
             * Status
             * @enum {string}
             */
            status: "validated" | "invalid_candidate" | "no_candidate" | "nothing_to_solve";
            /** Vehicle Types */
            vehicle_types?: string[] | null;
        };
        /**
         * WarmStartPlan
         * @description The warm-start source interface (spec §10, M6): a plan as routes of visits with their
         *     location and load, per source cluster, and the travel it was validated on. Its content hash is
         *     the plan identity recorded in the `warm_start` stage artifact and the replay bundle.
         */
        WarmStartPlan: {
            /** Clusters */
            clusters: components["schemas"]["WarmStartCluster"][];
            /** Fleet */
            fleet?: string[] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            source: components["schemas"]["WarmStartSource"];
            travel: components["schemas"]["WarmStartTravel"];
        };
        /**
         * WarmStartSource
         * @description Where a warm start's plan comes from (spec §10, M6). Today only a succeeded pipeline run the
         *     submitter can read; the web resolves it with owner checks and the worker receives its validated
         *     plan over the loopback transport as a `WarmStartPlan`. Another source (a saved manual baseline)
         *     would be a new `kind` producing the same plan document.
         */
        WarmStartSource: {
            /**
             * Kind
             * @default run
             * @constant
             */
            kind: "run";
            /** Run Id */
            run_id: string;
        };
        /** WarmStartSummary */
        WarmStartSummary: {
            /** Plan Id */
            plan_id: string;
            /** Skipped */
            skipped: number;
            source: components["schemas"]["WarmStartSource"];
            /** Used */
            used: number;
        };
        /**
         * WarmStartTravel
         * @description The travel identity the source plan was validated on: estimated haversine × circuity, or
         *     a stored directed snapshot.
         */
        WarmStartTravel: {
            /**
             * Circuity
             * @default null
             */
            circuity: number | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "estimated" | "snapshot";
            /**
             * Snapshot Id
             * @default null
             */
            snapshot_id: string | null;
        };
        /** WarmStartVisit */
        WarmStartVisit: {
            /** Load */
            load: number;
            /** Location Id */
            location_id: string;
            /** Visit Id */
            visit_id: string;
        };
        /** WorkerEvent */
        WorkerEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "progress" | "succeeded" | "failed" | "cancelled";
            lease: components["schemas"]["Lease"];
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Sequence */
            sequence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    post_evaluate_evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
