/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Behavior */
        Behavior: {
            /**
             * Availability
             * @default implemented
             * @enum {string}
             */
            availability: "implemented" | "planned" | "unsupported";
            /** Description */
            description: string;
            /** Fixture */
            fixture: string | null;
            /** Id */
            id: string;
            /**
             * Provided By
             * @enum {string}
             */
            provided_by: "native" | "preprocessing" | "workaround" | "validation";
            /**
             * Restrictions
             * @default []
             */
            restrictions: string[];
        };
        /** Capabilities */
        Capabilities: {
            /**
             * Adapter Version
             * @default pyvrp-partition/1
             */
            adapter_version: string;
            /** Behaviors */
            behaviors: components["schemas"]["Behavior"][];
            defaults: components["schemas"]["Defaults"];
            limits: components["schemas"]["Limits"];
            /** Platform */
            platform: string;
            /** Python */
            python: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Travel Modes */
            travel_modes: string[];
            units: components["schemas"]["Units"];
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** ClusterSummary */
        ClusterSummary: {
            /** Avg Fill */
            avg_fill: number | null;
            /** Capacity Lower Bound */
            capacity_lower_bound: number;
            /** Diameter M */
            diameter_m: number;
            /** Distance Bound M */
            distance_bound_m: number | null;
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Iterations */
            iterations: number;
            /** Load */
            load: number;
            /** Loaded Distance M */
            loaded_distance_m: number;
            /** Location Ids */
            location_ids: string[];
            /** Mean Centroid Distance M */
            mean_centroid_distance_m: number;
            /** Min Fill */
            min_fill: number | null;
            /** Objective Mode */
            objective_mode: string;
            /** Planned Amount Cents */
            planned_amount_cents: number;
            /** Planned Visit Count */
            planned_visit_count: number;
            /** Runtime S */
            runtime_s: number;
            /** Solver Feasible */
            solver_feasible: boolean | null;
            /**
             * Status
             * @enum {string}
             */
            status: "validated" | "invalid_candidate" | "no_candidate" | "nothing_to_solve";
            /** Truck Penalty */
            truck_penalty: number;
            /** Trucks */
            trucks: number;
            /** Violations */
            violations: string[];
            /** Visit Count */
            visit_count: number;
        };
        /** ClusteringSummary */
        ClusteringSummary: {
            /** Auto Limit Reached */
            auto_limit_reached: boolean;
            /** Effective Cluster Count */
            effective_cluster_count: number;
            /** Fits */
            fits: number;
            /** Raw Cluster Count */
            raw_cluster_count: number;
            /** Repairs */
            repairs: components["schemas"]["Repair"][];
            /** Requested K */
            requested_k: number | null;
            /** Selected K */
            selected_k: number | null;
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "kmeans" | "none";
        };
        /** ContractBundle */
        ContractBundle: {
            event: components["schemas"]["WorkerEvent"];
            manifest: components["schemas"]["StageManifest"];
            snapshot: components["schemas"]["Snapshot"];
        };
        /** Defaults */
        Defaults: {
            /**
             * Circuity
             * @default 1.2
             */
            circuity: number;
            /** Max Cluster Diameter M */
            max_cluster_diameter_m?: number | null;
            /**
             * Max Leg M
             * @default 804672
             */
            max_leg_m: number;
            /**
             * Trailer Capacity
             * @default 5300
             */
            trailer_capacity: number;
        };
        /** Depot */
        Depot: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** Diagnostic */
        Diagnostic: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
        };
        /** InventoryItem */
        InventoryItem: {
            /** Available Pieces */
            available_pieces: number;
            /** Product Id */
            product_id: string;
        };
        JsonValue: unknown;
        /** Lease */
        Lease: {
            /** Attempt */
            attempt: number;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Lease Token
             * Format: uuid
             */
            lease_token: string;
            /** Worker Id */
            worker_id: string;
        };
        /** Limits */
        Limits: {
            /**
             * Max Orders
             * @default 5000
             */
            max_orders: number;
            /**
             * Max Stops Per Solve
             * @default 500
             */
            max_stops_per_solve: number;
            /**
             * Run Wall Limit Seconds
             * @default 600
             */
            run_wall_limit_seconds: number;
            /**
             * Solve Attempt Limit Seconds
             * @default 300
             */
            solve_attempt_limit_seconds: number;
        };
        /** LineOnBoard */
        LineOnBoard: {
            /** Amount Cents */
            amount_cents: number;
            /** Line Id */
            line_id: string;
            /** Linear Feet */
            linear_feet: number;
            /** Order Id */
            order_id: string;
            /** Pieces */
            pieces: number;
            /** Product Id */
            product_id: string;
        };
        /** Location */
        Location: {
            /**
             * Coordinate Source
             * @enum {string}
             */
            coordinate_source: "imported" | "manual" | "census" | "zcta" | "unresolved";
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
        };
        /** MapLocation */
        MapLocation: {
            /** Cluster Id */
            cluster_id: string | null;
            /**
             * Coordinate Source
             * @enum {string}
             */
            coordinate_source: "imported" | "manual" | "census" | "zcta" | "unresolved";
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "planned" | "partial" | "unplanned" | "excluded" | "no_demand";
        };
        /** Order */
        Order: {
            /**
             * Customer Id
             * @default null
             */
            customer_id: string | null;
            /** Id */
            id: string;
            /** Lines */
            lines: components["schemas"]["OrderLine"][];
            /** Location Id */
            location_id: string;
            /** Order Date */
            order_date: string;
        };
        /** OrderLine */
        OrderLine: {
            /** Id */
            id: string;
            /**
             * Linear Feet Per Piece
             * @default null
             */
            linear_feet_per_piece: number | null;
            /** Net Value Per Piece Cents */
            net_value_per_piece_cents: number;
            /** Ordered Pieces */
            ordered_pieces: number;
            /** Product Id */
            product_id: string;
        };
        /**
         * PreflightFinding
         * @description One preflight check that found something. `action` is what the run did about it.
         */
        PreflightFinding: {
            /**
             * Action
             * @enum {string}
             */
            action: "block" | "warn";
            /**
             * Check
             * @enum {string}
             */
            check: "missing_coordinates" | "far_from_depot" | "oversize_stop" | "far_via_stop" | "approximate_coordinates";
            /** Line Ids */
            line_ids: string[];
            /** Location Ids */
            location_ids: string[];
            /** Message */
            message: string;
        };
        /**
         * PreflightPolicy
         * @description M2 scope item 8: which preflight checks stop a run. Policy, not physics (§7).
         *
         *     Round two (spec v1.9): `far_from_depot` covers only stops no chain of allowed drives
         *     reaches; a far stop reachable through another stop is the warning `far_via_stop`. A stop
         *     larger than one trailer splits across shipments by default.
         */
        PreflightPolicy: {
            /**
             * Far From Depot
             * @default block
             * @enum {string}
             */
            far_from_depot: "block" | "warn";
            /**
             * Missing Coordinates
             * @default block
             * @enum {string}
             */
            missing_coordinates: "block" | "warn";
            /**
             * Oversize Stop
             * @default warn
             * @enum {string}
             */
            oversize_stop: "block" | "warn";
        };
        /** Product */
        Product: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Linear Feet Per Piece */
            linear_feet_per_piece: number;
        };
        /** ProductReconciliation */
        ProductReconciliation: {
            /** Allocated */
            allocated: number;
            /** Allocated Cents */
            allocated_cents: number;
            /** Allocated Unplanned */
            allocated_unplanned: number;
            /** Eligible */
            eligible: number;
            /** Excluded */
            excluded: number;
            /** Label */
            label: string;
            /** Ordered */
            ordered: number;
            /** Ordered Cents */
            ordered_cents: number;
            /** Planned */
            planned: number;
            /** Planned Cents */
            planned_cents: number;
            /** Product Id */
            product_id: string;
            /** Residual */
            residual: number;
            /** Starting Inventory */
            starting_inventory: number;
            /** Unselected */
            unselected: number;
        };
        /** Repair */
        Repair: {
            /** Detail */
            detail: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "diameter" | "solve_size" | "degenerate_size";
        };
        /** RunSettings */
        RunSettings: {
            /**
             * Auto K Cap
             * @default 25
             */
            auto_k_cap: number;
            /**
             * Cluster Circuity
             * @default 1.2
             */
            cluster_circuity: number;
            /**
             * Cost Per Mile Cents
             * @default null
             */
            cost_per_mile_cents: number | null;
            /**
             * Cost Per Truck Cents
             * @default null
             */
            cost_per_truck_cents: number | null;
            /** Excluded Line Ids */
            excluded_line_ids?: string[];
            /**
             * K
             * @default null
             */
            k: number | null;
            /**
             * Kmeans N Init
             * @default 10
             */
            kmeans_n_init: number;
            /**
             * Kmeans Seed
             * @default 0
             */
            kmeans_seed: number;
            /**
             * Max Cluster Diameter M
             * @default null
             */
            max_cluster_diameter_m: number | null;
            /**
             * Max Leg M
             * @default 804672
             */
            max_leg_m: number;
            /**
             * Max Stops
             * @default 500
             */
            max_stops: number;
            /**
             * Objective
             * @default trucks_then_distance
             * @enum {string}
             */
            objective: "trucks_then_distance" | "weighted_distance" | "cost";
            preflight?: components["schemas"]["PreflightPolicy"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Solver Max Iterations
             * @default null
             */
            solver_max_iterations: number | null;
            /**
             * Solver Seed
             * @default 0
             */
            solver_seed: number;
            /**
             * Solver Time Limit S
             * @default 10
             */
            solver_time_limit_s: number;
            /**
             * Trailer Capacity
             * @default 5300
             */
            trailer_capacity: number;
            /**
             * Travel Circuity
             * @default 1.2
             */
            travel_circuity: number;
            /**
             * Weighted Truck Penalty M
             * @default null
             */
            weighted_truck_penalty_m: number | null;
        };
        /** RunSummary */
        RunSummary: {
            clustering: components["schemas"]["ClusteringSummary"];
            /** Clusters */
            clusters: components["schemas"]["ClusterSummary"][];
            /**
             * Coverage
             * @enum {string}
             */
            coverage: "complete" | "partial" | "empty";
            depot: components["schemas"]["Depot"];
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Locations */
            locations: components["schemas"]["MapLocation"][];
            /** Preflight */
            preflight?: components["schemas"]["PreflightFinding"][];
            /** Products */
            products: components["schemas"]["ProductReconciliation"][];
            /**
             * Proof
             * @default heuristic
             * @constant
             */
            proof: "heuristic";
            /** Scenario Name */
            scenario_name: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            settings: components["schemas"]["RunSettings"];
            totals: components["schemas"]["Totals"];
            /** Trucks */
            trucks: components["schemas"]["TruckSummary"][];
            /** Unplanned */
            unplanned: components["schemas"]["UnplannedLine"][];
            /**
             * Validity
             * @enum {string}
             */
            validity: "valid" | "invalid";
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** ScenarioDocument */
        ScenarioDocument: {
            depot: components["schemas"]["Depot"];
            /** Inventory */
            inventory: components["schemas"]["InventoryItem"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Name */
            name: string;
            /** Orders */
            orders: components["schemas"]["Order"][];
            /** Products */
            products: components["schemas"]["Product"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** Snapshot */
        Snapshot: {
            /** Document */
            document: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** StageManifest */
        StageManifest: {
            /** Adapter Version */
            adapter_version: string;
            /** Created At Ms */
            created_at_ms: number;
            /** Effective Settings */
            effective_settings: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Input Hash */
            input_hash: string;
            /** Output Hash */
            output_hash: string;
            /** Parent Hashes */
            parent_hashes: string[];
            /** Producer Version */
            producer_version: string;
            /**
             * Reused From
             * @default null
             */
            reused_from: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Stage Type
             * @enum {string}
             */
            stage_type: "preflight" | "allocation" | "aggregation" | "clustering" | "travel" | "problem" | "solve" | "validation" | "summary";
        };
        /** Totals */
        Totals: {
            /** Allocated Cents */
            allocated_cents: number;
            /** Avg Fill */
            avg_fill: number | null;
            /** Capacity Lower Bound */
            capacity_lower_bound: number;
            /** Load */
            load: number;
            /** Loaded Distance M */
            loaded_distance_m: number;
            /** Locations */
            locations: number;
            /** Min Fill */
            min_fill: number | null;
            /** Ordered Cents */
            ordered_cents: number;
            /** Planned Cents */
            planned_cents: number;
            /** Planned Visits */
            planned_visits: number;
            /** Sum Cluster Lower Bounds */
            sum_cluster_lower_bounds: number;
            /** Trucks */
            trucks: number;
            /** Utilization */
            utilization: number | null;
            /** Visits */
            visits: number;
        };
        /** TruckSummary */
        TruckSummary: {
            /** Amount Cents */
            amount_cents: number;
            /** Cluster Id */
            cluster_id: string;
            /** Distance M */
            distance_m: number;
            /** Fill */
            fill: number;
            /** Id */
            id: string;
            /** Load */
            load: number;
            /** Visits */
            visits: components["schemas"]["TruckVisit"][];
        };
        /** TruckVisit */
        TruckVisit: {
            /** Leg M */
            leg_m: number;
            /** Lines */
            lines: components["schemas"]["LineOnBoard"][];
            /** Load */
            load: number;
            /** Location Id */
            location_id: string;
            /** Sequence */
            sequence: number;
            /** Visit Id */
            visit_id: string;
        };
        /** Units */
        Units: {
            /**
             * Distance
             * @default meters (integer)
             */
            distance: string;
            /**
             * Linear Feet
             * @default hundredths of a foot (integer)
             */
            linear_feet: string;
            /**
             * Money
             * @default cents (integer)
             */
            money: string;
        };
        /** UnplannedLine */
        UnplannedLine: {
            /** Amount Cents */
            amount_cents: number;
            /** Evidence */
            evidence: string;
            /** Line Id */
            line_id: string;
            /** Location Id */
            location_id: string;
            /** Order Id */
            order_id: string;
            /** Pieces */
            pieces: number;
            /** Product Id */
            product_id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "excluded_unresolved_coordinates" | "excluded_by_user" | "oversize_piece" | "stock_shortage" | "unreachable" | "unreachable_in_partition" | "candidate_invalid" | "no_valid_candidate";
            /**
             * Stage
             * @enum {string}
             */
            stage: "preflight" | "allocation" | "problem" | "solve" | "validation";
        };
        /** WorkerEvent */
        WorkerEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "progress" | "succeeded" | "failed" | "cancelled";
            lease: components["schemas"]["Lease"];
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Sequence */
            sequence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
