import "server-only";
import type { LabInstance, LabResult } from "@fillrate/contracts";
import type { Store } from "@fillrate/db";
import { enqueueLabRun, LabInstanceError, labExampleVersion, labRun, validateLabInstance } from "@fillrate/db/lab";

import { accessError, admission, requireOwner, syntheticAdmission, type Principal } from "./access";
import { ApiError } from "./errors";
import { baseDetail } from "./runs";

import dimensions from "../../../../../examples/lab-dimensions.json";
import dimensionsVolume from "../../../../../examples/lab-dimensions-volume.json";
import fleet from "../../../../../examples/lab-fleet.json";
import fleetTrucks from "../../../../../examples/lab-fleet-trucks.json";
import depots from "../../../../../examples/lab-depots.json";
import depotsSingle from "../../../../../examples/lab-depots-single.json";
import groups from "../../../../../examples/lab-groups.json";
import groupsSouth from "../../../../../examples/lab-groups-south.json";
import prizes from "../../../../../examples/lab-prizes.json";
import prizesHigh from "../../../../../examples/lab-prizes-high.json";
import reloads from "../../../../../examples/lab-reloads.json";
import reloadsOff from "../../../../../examples/lab-reloads-off.json";

// Bundled Solver Lab examples (spec §13), generated by `fillrate_optimizer.lab.examples`. Every observation listed
// here is asserted in services/optimizer/tests/test_lab_examples.py. Like the lesson examples they are public:
// anyone allowed to start synthetic runs may run them unchanged.
export const LAB_EXAMPLES = {
  dimensions: {
    id: "dimensions", label: "Two dimensions", instance: dimensions as unknown as LabInstance,
    observations: ["Weight sets the truck count: 3 trucks carry 2,860 kg at 1,200 kg each, while no truck fills even 60% of its 4,000 L.", "Every seed from 0 to 3 finds the same objective."],
  },
  dimensions_volume: {
    id: "dimensions_volume", label: "Volume only", instance: dimensionsVolume as unknown as LabInstance,
    observations: ["Without the weight dimension 2 trucks suffice and the objective drops.", "Checked against the two-dimension instance, both of those trucks are over 1,200 kg: the plan is only valid because weight was left out."],
  },
  fleet: {
    id: "fleet", label: "Mixed fleet", instance: fleet as unknown as LabInstance,
    observations: ["All 3 cargo vans are used (their count binds) plus 1 box truck.", "Fixed costs are 3 × 15,000 + 40,000 = 85,000 cost units."],
  },
  fleet_trucks: {
    id: "fleet_trucks", label: "Trucks only", instance: fleetTrucks as unknown as LabInstance,
    observations: ["The same 30 pallets need 3 box trucks.", "Both fixed and total costs are higher than with the mixed fleet."],
  },
  depots: {
    id: "depots", label: "Two depots", instance: depots as unknown as LabInstance,
    observations: ["Two West vans start and end at the West depot and two East vans at the East depot; every route serves only the stops on its own side (6 West and 6 East stops, 3 per route).", "The objective is 689 cost units for every seed from 0 to 3: 400 fixed plus 289 distance."],
  },
  depots_single: {
    id: "depots_single", label: "One depot", instance: depotsSingle as unknown as LabInstance,
    observations: ["The same 12 stops and 4 vans, all based at the West depot: the two East routes now drive out from the West depot, so every East route is longer than 200 planar units.", "The objective is 1,096 cost units, over 1.5 times the two-depot plan; the fixed cost (400) is unchanged, so the difference is distance."],
  },
  reloads: {
    id: "reloads", label: "Reloads", instance: reloads as unknown as LabInstance,
    observations: ["One van of 10 parcels serves all 40 parcels: a single route of 4 trips, each carrying exactly 10 (100% full), the first from the DC to the yard and the last from the yard back to the DC.", "The objective is 533 cost units: one van's fixed cost of 100 plus 433 distance."],
  },
  reloads_off: {
    id: "reloads_off", label: "Reloads off", instance: reloadsOff as unknown as LabInstance,
    observations: ["Without reloading the same 8 stops need 4 vans, each driving one trip from the DC: fixed cost 400 and 780 distance.", "The objective is 1,180 cost units, over twice the reloading plan; the one reloading van also works longer than any single-trip van."],
  },
  prizes: {
    id: "prizes", label: "Optional stops", instance: prizes as unknown as LabInstance,
    observations: ["The three remote stops are optional with a prize of 60 each; the solver skips all three and the 5 required stops ride on 1 van.", "Nominal cost 315 (100 fixed + 215 distance) plus 180 of uncollected prizes: PyVRP minimizes 495. The prizes are a separate term, never part of the cost."],
  },
  prizes_high: {
    id: "prizes_high", label: "Higher prizes", instance: prizesHigh as unknown as LabInstance,
    observations: ["With a prize of 400 each, all 3 remote stops are visited on a second van: 2 routes, nominal cost 800, no uncollected prizes and 1,200 of prizes collected.", "The nominal cost is higher than when the stops were skipped (800 against 315), but skipping them would now cost 1,200 in prizes."],
  },
  groups: {
    id: "groups", label: "Alternative docks", instance: groups as unknown as LabInstance,
    observations: ["Customer Acme can be served at its north or its south dock: one required group, so exactly one dock is visited. With the four required stops on the north side the solver picks the north dock.", "One van serves all five visits at a nominal cost of 312 (100 fixed + 212 distance). Serving the south dock instead is valid but costs more."],
  },
  groups_south: {
    id: "groups_south", label: "Docks, stops south", instance: groupsSouth as unknown as LabInstance,
    observations: ["The same docks with the four required stops moved to the south side: now the south dock wins.", "The instance is the mirror image, so the nominal cost is again 312; only which alternative serves Acme changes."],
  },
} as const;
export type LabExampleId = keyof typeof LAB_EXAMPLES;
export type LabExample = (typeof LAB_EXAMPLES)[LabExampleId];

export const labExampleInfo = (example: LabExample) => ({
  id: example.id, label: example.label, name: example.instance.name, description: example.instance.description ?? "",
  coordinates: example.instance.coordinates, clients: example.instance.clients.length, dimensions: example.instance.dimensions.length,
  vehicle_types: example.instance.vehicle_types.length, observations: [...example.observations],
});

export const pageLabExample = (param: unknown): LabExample =>
  typeof param === "string" && Object.hasOwn(LAB_EXAMPLES, param) ? LAB_EXAMPLES[param as LabExampleId] : LAB_EXAMPLES.dimensions;

function parseLabExample(input: unknown): LabExample {
  if (typeof input === "string" && Object.hasOwn(LAB_EXAMPLES, input)) return LAB_EXAMPLES[input as LabExampleId];
  throw new ApiError(400, "unknown_example", `Unknown lab example; use one of ${Object.keys(LAB_EXAMPLES).join(", ")}.`, ["example"]);
}

/** Which bundled lab example a version holds, if any. */
export function labExampleForVersion(store: Store, versionId: string): LabExampleId | null {
  for (const example of Object.values(LAB_EXAMPLES)) if (labExampleVersion(store, example.instance) === versionId) return example.id;
  return null;
}

/** Owners may run their own instance JSON; everyone allowed synthetic runs may run a bundled example unchanged. */
export const canRunCustomLab = (who: Principal) => who.ownerId !== null;

/**
 * Queues a lab run. Body: `{ example }` (a bundled instance, public synthetic admission) or `{ instance }` (an
 * instance owned by the caller: operator/local mode or a signed-in account, charged like any solve).
 */
export function createLabRun(store: Store, who: Principal, body: { example?: unknown; instance?: unknown }, idempotencyKey: string) {
  if (!idempotencyKey || idempotencyKey.length > 200) throw new ApiError(400, "invalid_idempotency_key", "Send an Idempotency-Key header (1–200 characters).", ["Idempotency-Key"]);
  const hasExample = body.example !== undefined && body.example !== null, hasInstance = body.instance !== undefined && body.instance !== null;
  if (hasExample === hasInstance) throw new ApiError(400, "invalid_request", "Send either example or instance.", ["example", "instance"]);
  try {
    if (hasExample) {
      const example = parseLabExample(body.example);
      const { ownerId, admission: charge } = syntheticAdmission(who);
      return enqueueLabRun(store, { versionId: labExampleVersion(store, example.instance) }, idempotencyKey, { ownerId, admission: charge });
    }
    if (who.kind === "pending") throw accessError(who);
    const ownerId = requireOwner(who);
    const instance = validateLabInstance(body.instance);
    return enqueueLabRun(store, { instance }, idempotencyKey, { ownerId, admission: admission(who), author: who.user?.name ?? "Solver Lab" });
  } catch (error) {
    if (error instanceof LabInstanceError) throw new ApiError(error.code === "lab_instance_too_large" ? 413 : 422, error.code, error.message, error.fields.length ? error.fields : ["instance"]);
    if (error instanceof Error && error.message === "idempotency_conflict") throw new ApiError(409, "idempotency_conflict", "This Idempotency-Key was already used for a different request.");
    throw error;
  }
}

export type LabRunDetail = ReturnType<typeof baseDetail> & { kind: "lab"; example: LabExampleId | null; instance: LabInstance; result: LabResult | null };

export function labRunDetail(store: Store, runId: string): LabRunDetail {
  const run = labRun(store, runId);
  if (!run) throw new ApiError(404, "run_not_found", "No lab run with this ID.");
  return { ...baseDetail(run.view), kind: "lab", example: labExampleForVersion(store, run.view.versionId), instance: run.instance, result: run.result };
}

/** Recent lab runs the caller can read: bundled examples plus their own instances. */
export function visibleLabRuns(store: Store, who: Principal) {
  return store.listRuns(200, who.ownerId).filter(run => run.kind === "lab").slice(0, 20);
}

/** JSON export: the instance, the validated result and the run's provenance, with a reproduction command. */
export function labExport(store: Store, runId: string) {
  const detail = labRunDetail(store, runId);
  return {
    schema_version: 1,
    kind: "lab_run_export",
    run: { id: detail.id, status: detail.status, created_at: detail.created_at, attempt: detail.attempt, attempts: detail.attempts, failure: detail.failure, stages: detail.stages, example: detail.example },
    instance: detail.instance,
    result: detail.result,
    reproduce: `Download ?format=python and run it from services/optimizer of a Fillrate checkout: uv run python fillrate-lab-${runId.slice(0, 8)}.py`,
  };
}

/**
 * A small reproduction script: the instance and the recorded outcome embedded as JSON, checked by the tested
 * `fillrate_optimizer.lab.replay` module. A JSON string literal is also a valid Python string literal.
 */
export function labReproductionScript(store: Store, runId: string) {
  const detail = labRunDetail(store, runId);
  if (!detail.result) throw new ApiError(409, "run_not_succeeded", "Only succeeded lab runs can be reproduced.");
  const r = detail.result;
  const expected = {
    run_id: runId, problem_fingerprint: r.problem_fingerprint, validated_feasible: r.validated_feasible, stopped_by: r.solver.stopped_by,
    objective_total: r.objective.total, routes: r.routes.map(route => ({ vehicle_type: route.vehicle_type, client_ids: route.visits.map(v => v.client_id) })),
  };
  return `"""Reproduce Fillrate Solver Lab run ${runId}.

Run from services/optimizer of a Fillrate checkout (pinned PyVRP 0.14.0, Python 3.13):

    uv run python ${`fillrate-lab-${runId.slice(0, 8)}.py`}

The problem fingerprint and validated feasibility must match. When the run stopped on its
iteration budget, the objective and routes must match too; a runtime-limited run depends on the
machine, so only its fingerprint and feasibility are compared.
"""

import json
import sys

from fillrate_optimizer.lab.replay import replay

INSTANCE = json.loads(${JSON.stringify(JSON.stringify(detail.instance))})
EXPECTED = json.loads(${JSON.stringify(JSON.stringify(expected))})

if __name__ == "__main__":
    sys.exit(replay(INSTANCE, EXPECTED))
`;
}

/** `?format=json` (default) or `?format=python` for a lab run, as a download. */
export function labExportResponse(store: Store, runId: string, format: string) {
  if (format !== "json" && format !== "python") throw new ApiError(400, "invalid_format", "Lab runs export as json or python.", ["format"]);
  const name = `fillrate-lab-${runId.slice(0, 8)}`;
  const [body, type, file] = format === "json"
    ? [JSON.stringify(labExport(store, runId), null, 1), "application/json", `${name}.json`]
    : [labReproductionScript(store, runId), "text/x-python; charset=utf-8", `${name}.py`];
  return new Response(body, { headers: { "Cache-Control": "private, no-store", "content-type": type, "content-disposition": `attachment; filename="${file}"` } });
}
