import Link from "next/link"

import { DevHeader } from "@/components/brand/dev-header"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { pagePrincipal } from "@/lib/server/access"
import { EXAMPLES, canStartRuns, exampleInfo, runsClosedNote } from "@/lib/server/runs"
import { METERS_PER_MILE } from "@/lib/shipment-sheet"
import { formatFeet, formatMiles } from "@/lib/units"
import type { TravelSnapshot } from "@fillrate/db/travel"

import { ModelFields } from "../lesson-kit"
import { MatrixSteps } from "./matrix-steps"

export const dynamic = "force-dynamic"
export const metadata = { title: "Lesson: Haversine versus recorded road matrices · Fillrate" }

const RIVER_EAST_MI = 40
const RIDGE_EAST_MI = 200
// Directed pairs worth reading: the ridge detour into the resort, both directions of one river crossing, and a pair
// whose recorded distance is about twice the estimate although neither end is beyond a barrier.
const PAIRS: [string, string, string][] = [
  ["DC-MEM", "RM-07", "Around the ridge: within 500 mi on the estimate, over 500 mi recorded"],
  ["RM-06", "RM-07", "The estimated plan reaches the resort on this leg"],
  ["RM-05", "RM-07", "The shortest recorded leg into the resort, still over 500 mi"],
  ["RM-03", "RM-04", "Eastbound over the one-way bridge"],
  ["RM-04", "RM-03", "The same pair westbound: the bridge 110 mi south"],
  ["RM-02", "RM-05", "Eastbound, but south of the one-way bridge"],
]

function haversineM(a: { lat: number; lon: number }, b: { lat: number; lon: number }) {
  const rad = (d: number) => (d * Math.PI) / 180
  const h = Math.sin(rad(b.lat - a.lat) / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(rad(b.lon - a.lon) / 2) ** 2
  return 2 * 6_371_008.8 * Math.asin(Math.sqrt(Math.min(1, Math.max(0, h))))
}

// Road matrix lesson (spec §7, §10, §13): one synthetic scenario on estimated travel and on a bundled recorded
// directed matrix. The matrix is synthetic, generated by fillrate_optimizer.lesson_matrix; it is not real roads.
export default async function RoadMatricesLessonPage({ searchParams }: PageProps<"/learn/road-matrices">) {
  const { key } = await searchParams
  const example = EXAMPLES.matrix_recorded
  const { scenario, settings } = example
  const snapshot = example.travel as TravelSnapshot
  const info = exampleInfo(example)
  const circuity = EXAMPLES.matrix_estimated.settings.travel_circuity ?? 1.2
  const index = new Map(snapshot.nodes.map((n, i) => [n.id, i]))
  const label = new Map<string, string>([[scenario.depot.id, scenario.depot.label ?? scenario.depot.id], ...scenario.locations.map((l) => [l.id, l.label ?? l.id] as [string, string])])
  const kmToMiles = (km: number) => (km * 1000) / METERS_PER_MILE
  const estimateMiles = (a: string, b: string) => (haversineM(snapshot.nodes[index.get(a)!], snapshot.nodes[index.get(b)!]) * circuity) / METERS_PER_MILE
  const recordedMiles = (a: string, b: string) => kmToMiles(snapshot.distances[index.get(a)!][index.get(b)!] ?? Number.NaN)
  const eastMiles = (lat: number, lon: number) => (lon - scenario.depot.lon) * 69.0934 * Math.cos((scenario.depot.lat * Math.PI) / 180)
  const side = (l: (typeof scenario.locations)[number]) => {
    const east = eastMiles(l.lat ?? 0, l.lon ?? 0)
    return east > RIDGE_EAST_MI ? "Beyond the ridge" : east > RIVER_EAST_MI ? "East of the river" : "West of the river (the DC's side)"
  }
  const feet = new Map(scenario.products.map((p) => [p.id, p.linear_feet_per_piece]))
  const pallets = new Map<string, number>()
  let load = 0
  for (const o of scenario.orders)
    for (const l of o.lines) {
      pallets.set(o.location_id, (pallets.get(o.location_id) ?? 0) + l.ordered_pieces)
      load += l.ordered_pieces * (feet.get(l.product_id) ?? 0)
    }
  const capacity = settings.trailer_capacity ?? 5300

  return (
    <div className="flex min-h-dvh flex-col">
      <DevHeader />
      <main className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-4 py-8 sm:px-6">
        <section className="flex flex-col gap-3">
          <Link href="/learn" className="text-muted-foreground text-sm underline underline-offset-4">Lessons</Link>
          <h1 className="text-2xl font-semibold tracking-tight">Haversine versus recorded road matrices</h1>
          <p className="text-muted-foreground max-w-2xl text-sm text-pretty">
            {info.orders} synthetic customers around a Memphis DC, planned twice. First on the default estimated travel: straight-line distance × {circuity} at a constant
            speed. Then on a recorded directed travel matrix, the kind of snapshot a road provider returns: one distance and one drive time for every ordered pair of
            places, so A → B need not equal B → A. Everything else is the same scenario, the same {formatFeet(capacity, 0)} trailers ({formatFeet(load, 0)} of freight in all), the
            same 500-mile limit on every single drive and one cluster (k = {info.k}). Every step starts a real run on this server; the numbers are what to look for, not
            fixed answers.
          </p>
          <p className="max-w-2xl rounded-xl border border-dashed p-3 text-sm text-pretty">
            <Badge variant="warning" className="mr-2">Synthetic</Badge>
            The recorded matrix in this lesson is synthetic: it stands in for a road-provider snapshot and is computed from an invented road network (a river with a
            one-way bridge, a ridge with one way around it). It is not real roads, and its numbers say nothing about real travel near Memphis.
          </p>
        </section>

        <section className="flex flex-col gap-3" aria-labelledby="stops">
          <h2 id="stops" className="text-sm font-medium">Customers</h2>
          <div className="overflow-x-auto rounded-xl border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Customer</TableHead>
                  <TableHead>Where</TableHead>
                  <TableHead className="text-right">Pallets</TableHead>
                  <TableHead className="text-right">From the DC, estimated</TableHead>
                  <TableHead className="text-right">From the DC, recorded</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {scenario.locations.map((l) => (
                  <TableRow key={l.id}>
                    <TableCell>{l.label} <span className="text-muted-foreground font-mono text-xs">{l.id}</span></TableCell>
                    <TableCell>{side(l)}</TableCell>
                    <TableCell className="text-right tabular-nums">{pallets.get(l.id) ?? 0}</TableCell>
                    <TableCell className="text-right tabular-nums">{formatMiles(estimateMiles(scenario.depot.id, l.id))}</TableCell>
                    <TableCell className="text-right tabular-nums">{formatMiles(recordedMiles(scenario.depot.id, l.id))}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>

        <section className="flex flex-col gap-3" aria-labelledby="detours">
          <h2 id="detours" className="text-sm font-medium">Where the two disagree</h2>
          <div className="overflow-x-auto rounded-xl border">
            <Table aria-label="Directed pairs: estimated and recorded miles">
              <TableHeader>
                <TableRow>
                  <TableHead>From → to</TableHead>
                  <TableHead className="text-right">Estimated</TableHead>
                  <TableHead className="text-right">Recorded</TableHead>
                  <TableHead>Why</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {PAIRS.map(([a, b, why]) => (
                  <TableRow key={`${a}-${b}`}>
                    <TableCell>{label.get(a)} → {label.get(b)}</TableCell>
                    <TableCell className="text-right tabular-nums">{formatMiles(estimateMiles(a, b))}</TableCell>
                    <TableCell className="text-right tabular-nums">{formatMiles(recordedMiles(a, b))}</TableCell>
                    <TableCell className="text-muted-foreground min-w-56 text-pretty">{why}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
          <dl className="text-muted-foreground grid gap-x-4 gap-y-1 text-xs sm:grid-cols-[max-content_minmax(0,1fr)]">
            <dt>Matrix</dt>
            <dd className="font-mono break-all">{settings.travel_snapshot_id}</dd>
            <dt>Provider</dt>
            <dd>{snapshot.provider} · {snapshot.provider_version} · {snapshot.dataset_revision} · {snapshot.profile}</dd>
            <dt>Units</dt>
            <dd>{snapshot.distance_units} and {snapshot.duration_units}, {snapshot.nodes.length} nodes, every directed pair recorded</dd>
          </dl>
        </section>

        <ModelFields
          fields={[
            ["settings.travel_snapshot_id", "The content hash of a stored, immutable directed travel snapshot. Null (step 1) means estimated travel; the recorded run names the bundled matrix. Legs, drive times, reachability and preflight all read the selected matrix."],
            ["settings.travel_circuity", `The estimate's factor (${circuity}): straight-line miles × ${circuity}. Not used for travel when a matrix is selected.`],
            ["settings.max_leg_m", "The 500-mile limit on each single drive (depot → first stop and stop → stop, not the return), measured in whichever travel the run uses."],
            ["settings.preflight.far_from_depot", "\"warn\" here: a stop no chain of allowed drives reaches is left unshipped as unreachable instead of blocking the run."],
            ["settings.solver_seed", "The PyVRP seed. With one cluster and a fixed iteration budget, seeds 0 to 3 give the same plan in both runs."],
          ]}
          notModeled="real road networks (the matrix is synthetic); traffic or time-of-day drive times; road geometry (paths on the map stay straight lines); a Valhalla server (no live road provider is used); a haversine fallback for missing legs; changing the cluster metric (clustering stays on straight-line distance in both runs)."
        />

        <MatrixSteps open={canStartRuns(await pagePrincipal(), key)} closedNote={runsClosedNote()} runKey={typeof key === "string" ? key : undefined} />
      </main>
    </div>
  )
}
